"""Deterministic SQL text emitter.  It never opens a database or executes output."""
import json


def sql_literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _text_array(values):
    if not values:
        return None
    return "ARRAY[" + ", ".join(sql_literal(v) for v in values) + "]::text[]"


def _values(rows, columns, transforms=None):
    transforms = transforms or {}
    out = []
    for row in rows:
        values = []
        for column in columns:
            value = row.get(column)
            if column in transforms: value = transforms[column](value)
            values.append("NULL" if value is None else (value if isinstance(value, str) and value.startswith("ARRAY[") else sql_literal(value)))
        out.append("(" + ", ".join(values) + ")")
    return ",\n".join(out) or "-- no rows"


def emit_sql(plan, generator_commit="uncommitted"):
    expected = json.dumps({"entries": plan.get("snapshot_entry_count", 0), "loci": len(plan.get("loci", []))}, ensure_ascii=False, sort_keys=True)
    lines = [
        "-- Phase 3 Qiraat migration; generated by %s" % generator_commit,
        "-- fixture_sha256=%s" % plan.get("fixture_sha256", ""),
        "-- snapshot_time=%s" % plan.get("snapshot_time", ""),
        "-- expected_counts=%s" % expected,
        "SET LOCAL app.device_id = 'phase3-migration';",
        "SET LOCAL standard_conforming_strings = on;",
        "DO $$ DECLARE n bigint; c text; BEGIN SELECT count(*) INTO n FROM quran_words; IF n <> 77429 THEN RAISE EXCEPTION 'quran_words count changed: %%', n; END IF; SELECT md5(string_agg(canonical_key || text_uthmani, '|' ORDER BY canonical_key)) INTO c FROM quran_words; IF c <> '52839d155fd0f90f999822a43e8198f5' THEN RAISE EXCEPTION 'quran_words checksum changed: %%', c; END IF; IF (SELECT count(*) FROM qiraat_entries) <> %d THEN RAISE EXCEPTION 'qiraat_entries snapshot count changed'; END IF; END $$;" % int(plan.get("snapshot_entry_count", 0)),
        "ALTER TABLE qiraat_entry_authorities DISABLE TRIGGER qiraat_entry_authorities_sync_trg;",
        "CREATE TEMP TABLE p3_pages (page_number smallint, source_page_number integer, surah_number smallint, surah_name_ar text, ayah_from smallint, ayah_to smallint, notes text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_loci (id text primary key, page_id bigint, surah_number smallint, start_ayah smallint, start_word smallint, end_ayah smallint, end_word smallint, location_order smallint, base_text text, base_text_normalized text, legacy_ref text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_entries (id text primary key, locus_id text, page_id bigint, page_number smallint, kind qiraat_entry_kind, entry_order smallint, attribution_mode qiraat_attribution_mode, verification_status qiraat_verification_status, review_status qiraat_review_status, legacy_ref text, notes text, deleted_at timestamptz) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_variant_details (entry_id text primary key, reading_text text, reading_text_normalized text, uthmani_text text, description_ar text, variant_type qiraat_variant_type, is_baseline_reading boolean, performance_note text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_ruling_details (entry_id text primary key, category_code text, rule_id text, text_ar text, options text[]) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_authorities (entry_id text, authority_id text, action_ar text, condition_ar text, is_default boolean, wajh_order smallint, wajh_note text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_flags (page_id bigint, locus_id text, entry_id text, severity qiraat_flag_severity, flag_type text, issue_ar text, original_text text, status qiraat_flag_status) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_drops (entry_id text primary key) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_count_schools (entry_id text, count_school_id text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_evidence (source_document_id text, text_ar text, text_normalized text, page_id bigint, locus_id text, evidence_order smallint) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_redirects (old_locus_id text, canonical_locus_id text) ON COMMIT DROP;",
        "CREATE TEMP TABLE p3_entry_orders (id text primary key, locus_id text, kind qiraat_entry_kind, entry_order smallint, temporary_order integer) ON COMMIT DROP;",
    ]
    loci_rows = []
    for locus in plan.get("loci", []):
        s = locus["span"]
        loci_rows.append({"id": locus["id"], "page_id": next((e.get("page_id") for e in plan.get("entries", []) if e["locus_id"] == locus["id"]), None), "surah_number": s[0], "start_ayah": s[1], "start_word": s[2], "end_ayah": s[3], "end_word": s[4], "location_order": locus.get("location_order"), "base_text": locus.get("base_text"), "base_text_normalized": locus.get("base_text_normalized"), "legacy_ref": locus.get("legacy_ref")})
    lines.append("INSERT INTO p3_pages VALUES\n" + _values(plan.get("pages", []), ["page_number", "source_page_number", "surah_number", "surah_name_ar", "ayah_from", "ayah_to", "notes"]) + ";")
    lines.append("INSERT INTO p3_loci VALUES\n" + _values(loci_rows, ["id", "page_id", "surah_number", "start_ayah", "start_word", "end_ayah", "end_word", "location_order", "base_text", "base_text_normalized", "legacy_ref"] ) + ";")
    lines.append("INSERT INTO p3_entries VALUES\n" + _values(plan.get("entries", []), ["id", "locus_id", "page_id", "page_number", "kind", "entry_order", "attribution_mode", "verification_status", "review_status", "legacy_ref", "notes", "deleted_at"]) + ";")
    lines.append("INSERT INTO p3_variant_details VALUES\n" + _values(plan.get("variant_details", []), ["entry_id", "reading_text", "reading_text_normalized", "uthmani_text", "description_ar", "variant_type", "is_baseline_reading", "performance_note"]) + ";")
    lines.append("INSERT INTO p3_ruling_details VALUES\n" + _values(plan.get("ruling_details", []), ["entry_id", "category_code", "rule_id", "text_ar", "options"], {"options": _text_array}) + ";")
    lines.append("INSERT INTO p3_authorities VALUES\n" + _values(plan.get("authorities", []), ["entry_id", "authority_id", "action_ar", "condition_ar", "is_default", "wajh_order", "wajh_note"]) + ";")
    lines.append("INSERT INTO p3_flags VALUES\n" + _values(plan.get("flags", []), ["page_id", "locus_id", "entry_id", "severity", "flag_type", "issue_ar", "original_text", "status"]) + ";")
    lines.append("INSERT INTO p3_drops VALUES\n" + _values(plan.get("drops", []), ["entry_id"]) + ";")
    lines.append("INSERT INTO p3_count_schools VALUES\n" + _values(plan.get("count_schools", []), ["entry_id", "count_school_id"]) + ";")
    lines.append("INSERT INTO p3_evidence VALUES\n" + _values(plan.get("evidence", []), ["source_document_id", "text_ar", "text_normalized", "page_id", "locus_id", "evidence_order"]) + ";")
    lines.append("INSERT INTO p3_redirects VALUES\n" + _values([{"old_locus_id": old, "canonical_locus_id": new} for old, new in plan.get("redirects", [])], ["old_locus_id", "canonical_locus_id"]) + ";")
    lines.append("INSERT INTO p3_entry_orders VALUES\n" + _values(plan.get("entry_orders", []), ["id", "locus_id", "kind", "entry_order", "temporary_order"]) + ";")
    lines += [
        "INSERT INTO qiraat_pages (source_document_id, source_page_number, mushaf_page_number, surah_number, surah_name_ar, ayah_from, ayah_to, extraction_status, notes) SELECT 'SRC-MUSHAF-10', source_page_number, page_number, surah_number, surah_name_ar, ayah_from, ayah_to, 'REVIEWED', notes FROM p3_pages ON CONFLICT (source_document_id, source_page_number) DO UPDATE SET mushaf_page_number=EXCLUDED.mushaf_page_number, surah_number=EXCLUDED.surah_number, ayah_from=EXCLUDED.ayah_from, ayah_to=EXCLUDED.ayah_to, extraction_status=EXCLUDED.extraction_status;",
        "UPDATE p3_loci l SET page_id=(SELECT min(p.id) FROM qiraat_pages p WHERE p.mushaf_page_number=(SELECT min(e.page_number) FROM p3_entries e WHERE e.locus_id=l.id));",
        "UPDATE p3_entries e SET page_id=(SELECT min(p.id) FROM qiraat_pages p WHERE p.mushaf_page_number=e.page_number) WHERE page_id IS NULL;",
        "UPDATE p3_flags f SET page_id=(SELECT e.page_id FROM p3_entries e WHERE e.id=f.entry_id) WHERE f.page_id IS NULL;",
        "UPDATE p3_evidence e SET page_id=(SELECT min(x.page_id) FROM p3_entries x WHERE x.locus_id=e.locus_id) WHERE e.page_id IS NULL;",
        "UPDATE qiraat_entries e SET entry_order = o.temporary_order FROM p3_entry_orders o WHERE e.id=o.id AND (e.entry_order IS DISTINCT FROM o.entry_order OR e.locus_id IS DISTINCT FROM o.locus_id OR e.kind IS DISTINCT FROM o.kind);",
        "INSERT INTO qiraat_loci (id, page_id, surah_number, start_ayah, start_word, end_ayah, end_word, location_order, base_text, base_text_normalized, mapping_status, review_status, legacy_ref) SELECT id, page_id, surah_number, start_ayah, start_word, end_ayah, end_word, location_order, base_text, base_text_normalized, 'verified', 'unreviewed', legacy_ref FROM p3_loci ON CONFLICT (id) DO UPDATE SET page_id=EXCLUDED.page_id, location_order=EXCLUDED.location_order, base_text=EXCLUDED.base_text, base_text_normalized=EXCLUDED.base_text_normalized, mapping_status=EXCLUDED.mapping_status, legacy_ref=EXCLUDED.legacy_ref WHERE qiraat_loci.page_id IS DISTINCT FROM EXCLUDED.page_id OR qiraat_loci.location_order IS DISTINCT FROM EXCLUDED.location_order OR qiraat_loci.base_text IS DISTINCT FROM EXCLUDED.base_text OR qiraat_loci.base_text_normalized IS DISTINCT FROM EXCLUDED.base_text_normalized OR qiraat_loci.legacy_ref IS DISTINCT FROM EXCLUDED.legacy_ref;",
        "INSERT INTO qiraat_entries (id, locus_id, page_id, kind, entry_order, attribution_mode, verification_status, review_status, legacy_ref, notes, deleted_at) SELECT id, locus_id, page_id, kind, entry_order, attribution_mode, verification_status, review_status, legacy_ref, notes, deleted_at FROM p3_entries ON CONFLICT (id) DO UPDATE SET locus_id=EXCLUDED.locus_id, page_id=EXCLUDED.page_id, kind=EXCLUDED.kind, entry_order=EXCLUDED.entry_order, attribution_mode=EXCLUDED.attribution_mode, verification_status=EXCLUDED.verification_status, review_status=EXCLUDED.review_status, legacy_ref=EXCLUDED.legacy_ref, notes=EXCLUDED.notes, deleted_at=EXCLUDED.deleted_at WHERE qiraat_entries.locus_id IS DISTINCT FROM EXCLUDED.locus_id OR qiraat_entries.page_id IS DISTINCT FROM EXCLUDED.page_id OR qiraat_entries.kind IS DISTINCT FROM EXCLUDED.kind OR qiraat_entries.entry_order IS DISTINCT FROM EXCLUDED.entry_order OR qiraat_entries.attribution_mode IS DISTINCT FROM EXCLUDED.attribution_mode OR qiraat_entries.verification_status IS DISTINCT FROM EXCLUDED.verification_status OR qiraat_entries.review_status IS DISTINCT FROM EXCLUDED.review_status OR qiraat_entries.legacy_ref IS DISTINCT FROM EXCLUDED.legacy_ref OR qiraat_entries.notes IS DISTINCT FROM EXCLUDED.notes OR qiraat_entries.deleted_at IS DISTINCT FROM EXCLUDED.deleted_at;",
        "UPDATE qiraat_entries e SET entry_order = o.entry_order FROM p3_entry_orders o WHERE e.id=o.id AND e.entry_order IS DISTINCT FROM o.entry_order;",
        "DELETE FROM qiraat_variant_details WHERE entry_id IN (SELECT entry_id FROM p3_ruling_details);",
        "DELETE FROM qiraat_ruling_details WHERE entry_id IN (SELECT entry_id FROM p3_variant_details);",
        "INSERT INTO qiraat_variant_details (entry_id, reading_text, reading_text_normalized, uthmani_text, description_ar, variant_type, is_baseline_reading, performance_note) SELECT * FROM p3_variant_details ON CONFLICT (entry_id) DO UPDATE SET reading_text=EXCLUDED.reading_text, reading_text_normalized=EXCLUDED.reading_text_normalized, uthmani_text=EXCLUDED.uthmani_text, description_ar=EXCLUDED.description_ar, variant_type=EXCLUDED.variant_type, is_baseline_reading=EXCLUDED.is_baseline_reading, performance_note=EXCLUDED.performance_note;",
        "INSERT INTO qiraat_ruling_details (entry_id, category_code, rule_id, text_ar, options) SELECT * FROM p3_ruling_details ON CONFLICT (entry_id) DO UPDATE SET category_code=EXCLUDED.category_code, rule_id=COALESCE(EXCLUDED.rule_id, qiraat_ruling_details.rule_id), text_ar=EXCLUDED.text_ar, options=EXCLUDED.options;",
        "INSERT INTO qiraat_entry_count_schools (entry_id, count_school_id) SELECT entry_id, count_school_id FROM p3_count_schools ON CONFLICT DO NOTHING;",
        "UPDATE qiraat_entry_authorities a SET deleted_at=now() WHERE a.deleted_at IS NULL AND a.entry_id IN (SELECT id FROM p3_entries WHERE legacy_ref NOT LIKE 'db-only:%') AND NOT EXISTS (SELECT 1 FROM p3_authorities p WHERE p.entry_id=a.entry_id AND p.authority_id=a.authority_id AND COALESCE(p.action_ar, '')=COALESCE(a.action_ar, ''));",
        "INSERT INTO qiraat_entry_authorities (entry_id, authority_id, action_ar, condition_ar, is_default, wajh_order, wajh_note) SELECT entry_id, authority_id, action_ar, condition_ar, is_default, wajh_order, wajh_note FROM p3_authorities ON CONFLICT (entry_id, authority_id, (COALESCE(action_ar, ''))) DO UPDATE SET condition_ar=EXCLUDED.condition_ar, is_default=EXCLUDED.is_default, wajh_order=EXCLUDED.wajh_order, wajh_note=EXCLUDED.wajh_note, deleted_at=NULL WHERE qiraat_entry_authorities.condition_ar IS DISTINCT FROM EXCLUDED.condition_ar OR qiraat_entry_authorities.is_default IS DISTINCT FROM EXCLUDED.is_default OR qiraat_entry_authorities.wajh_order IS DISTINCT FROM EXCLUDED.wajh_order OR qiraat_entry_authorities.wajh_note IS DISTINCT FROM EXCLUDED.wajh_note OR qiraat_entry_authorities.deleted_at IS DISTINCT FROM NULL;",
        "INSERT INTO qiraat_source_documents (id, name_ar, document_type, notes) SELECT DISTINCT source_document_id, source_document_id, 'other', 'Fixture evidence label; bibliographic metadata requires editorial enrichment.' FROM p3_evidence WHERE source_document_id IS NOT NULL ON CONFLICT (id) DO NOTHING;",
        "INSERT INTO qiraat_evidence_texts (source_document_id, text_ar, text_normalized) SELECT DISTINCT ON (source_document_id, text_normalized) source_document_id, text_ar, text_normalized FROM p3_evidence WHERE source_document_id IS NOT NULL ORDER BY source_document_id, text_normalized, text_ar ON CONFLICT (source_document_id, text_normalized) DO UPDATE SET text_ar=EXCLUDED.text_ar;",
        "WITH ranked AS (SELECT old.id, row_number() OVER (PARTITION BY r.canonical_locus_id, old.evidence_text_id, old.page_id ORDER BY old.id) AS rn FROM qiraat_evidence_links old JOIN p3_redirects r ON r.old_locus_id=old.locus_id) DELETE FROM qiraat_evidence_links old USING ranked d WHERE old.id=d.id AND d.rn > 1;",
        "DELETE FROM qiraat_evidence_links old USING p3_redirects r WHERE old.locus_id=r.old_locus_id AND EXISTS (SELECT 1 FROM qiraat_evidence_links keep WHERE keep.evidence_text_id=old.evidence_text_id AND keep.page_id=old.page_id AND keep.locus_id=r.canonical_locus_id);",
        "UPDATE qiraat_evidence_links old SET locus_id=r.canonical_locus_id FROM p3_redirects r WHERE old.locus_id=r.old_locus_id;",
        "INSERT INTO qiraat_evidence_links (evidence_text_id, page_id, locus_id, evidence_order) SELECT t.id, e.page_id, e.locus_id, e.evidence_order FROM (SELECT DISTINCT ON (source_document_id, text_normalized, page_id, locus_id) * FROM p3_evidence ORDER BY source_document_id, text_normalized, page_id, locus_id, evidence_order) e JOIN qiraat_evidence_texts t ON t.source_document_id=e.source_document_id AND t.text_normalized=e.text_normalized ON CONFLICT (evidence_text_id, page_id, locus_id) DO UPDATE SET evidence_order=EXCLUDED.evidence_order;",
        "UPDATE qiraat_entries e SET locus_id=r.canonical_locus_id FROM p3_redirects r WHERE e.locus_id=r.old_locus_id AND e.verification_status <> 'REJECTED' AND e.deleted_at IS NULL;",
        "UPDATE qiraat_entries SET deleted_at=now() WHERE id IN (SELECT entry_id FROM p3_drops);",
        "UPDATE qiraat_loci SET deleted_at=now() WHERE id IN (" + ",".join(sql_literal(x) for x in plan.get("emptied_loci", [])) + ") AND deleted_at IS NULL;" if plan.get("emptied_loci") else "-- no emptied loci",
        "DELETE FROM qiraat_qa_flags WHERE status='open' AND flag_type IN ('D8_HAFS_KEPT','NEEDS_MANUAL_REVIEW','DOCUMENTED_CONFLICT','ATTRIBUTION_MISMATCH','NARRATOR_TWICE','Q6_AMBIGUOUS','DB_ONLY','UNKNOWN_CATEGORY') AND issue_ar LIKE '[phase3] %';",
        "INSERT INTO qiraat_qa_flags (page_id, locus_id, entry_id, severity, flag_type, issue_ar, original_text, status) SELECT * FROM p3_flags;",
        "UPDATE qiraat_loci l SET review_status='flagged' WHERE l.id IN (SELECT DISTINCT locus_id FROM p3_flags WHERE locus_id IS NOT NULL);",
    ]
    touched = sorted(set(plan.get("touched_loci", [])))
    if touched:
        lines.append("SELECT count(qiraat_rebuild_locus_readings(id)) FROM qiraat_loci WHERE id IN (" + ",".join(sql_literal(x) for x in touched) + ");")
    lines += [
        "ALTER TABLE qiraat_entry_authorities ENABLE TRIGGER qiraat_entry_authorities_sync_trg;",
        "SET CONSTRAINTS ALL IMMEDIATE;",
        "DO $$ BEGIN IF (SELECT count(*) FROM quran_words) <> 77429 THEN RAISE EXCEPTION 'quran_words changed'; END IF; IF EXISTS (SELECT 1 FROM qiraat_qa_phase2_violations v LEFT JOIN qiraat_entries e ON e.id=v.entry_id LEFT JOIN qiraat_loci l ON l.id=v.locus_id WHERE COALESCE(e.review_status, l.review_status, 'unreviewed') <> 'flagged') THEN RAISE EXCEPTION 'non-flagged Phase 2 violations remain'; END IF; IF EXISTS (SELECT 1 FROM qiraat_qa_phase2_violations WHERE rule='EMPTY_LOCATION') THEN RAISE EXCEPTION 'empty locations remain'; END IF; IF EXISTS (SELECT 1 FROM qiraat_entry_readings er JOIN qiraat_entries e ON e.id=er.entry_id WHERE e.deleted_at IS NULL AND e.verification_status <> 'REJECTED' AND e.review_status <> 'flagged' AND er.reading_id='Q05-R02' AND er.wajh_order=1) THEN RAISE EXCEPTION 'non-flagged Hafs main reading remains'; END IF; END $$;",
    ]
    return "\n\n".join(lines) + "\n"
