window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[106] = [];
window.AUTOMATED_SURAH_DATA["قريش"] = window.AUTOMATED_SURAH_DATA_BY_NO[106];
