window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[92] = [];
window.AUTOMATED_SURAH_DATA["الليل"] = window.AUTOMATED_SURAH_DATA_BY_NO[92];
