window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[108] = [];
window.AUTOMATED_SURAH_DATA["الكوثر"] = window.AUTOMATED_SURAH_DATA_BY_NO[108];
