window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[100] = [];
window.AUTOMATED_SURAH_DATA["العاديات"] = window.AUTOMATED_SURAH_DATA_BY_NO[100];
