window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[94] = [];
window.AUTOMATED_SURAH_DATA["الشرح"] = window.AUTOMATED_SURAH_DATA_BY_NO[94];
