function exportActiveDatabase(){if(!activeDb)return alert('افتح قاعدة أولاً');let vn=activeDb==='personal'?'PERSONAL_DATA':'AUTOMATED_DATA',fn=activeDb==='personal'?'personal-data.js':'automated-data.js',blob=new Blob(['window.'+vn+' = '+JSON.stringify(activeData,null,2)+';\n'],{type:'application/javascript;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fn;a.click()}

function htmlToPlainText(v){let d=document.createElement('div');d.innerHTML=safeText(v);return (d.textContent||d.innerText||'').trim()}

function groupPlainText(g){return [`عنوان المتشابه:\n${safeText(g.title||'بدون عنوان')}`,`رقم المجموعة: ${safeText(g.id)}`,`السور: ${getTags(g).join(' / ')}`,'الآيات:',...(g.verses||[]).map((v,i)=>`${i+1}. سورة ${safeText(v.surah)} — آية ${safeText(v.ayah)}${v.label?' — '+safeText(v.label):''}\n${(v.parts||[]).map(p=>safeText(p.text)).join(' ')}`),g.note?`ملاحظة:\n${htmlToPlainText(g.note)}`:'',g.unote?`فائدة إضافية:\n${htmlToPlainText(g.unote)}`:''].filter(Boolean).join('\n\n')}

async function writeClipboardTextV78(txt){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(txt);return true}}catch(e){}try{let ta=document.createElement('textarea');ta.value=txt;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.top='0';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();ta.setSelectionRange(0,ta.value.length);let ok=document.execCommand('copy');ta.remove();return ok}catch(e){return false}}

const SHARE_COLORS_V78={normal:{fg:'#111827',bg:null},shared:{fg:'#15803d',bg:'#dcfce7'},diff:{fg:'#92400e',bg:'#fef3c7'},diff2:{fg:'#6d28d9',bg:'#ede9fe'},diff3:{fg:'#0f766e',bg:'#ccfbf1'},addition:{fg:'#1d4ed8',bg:'#dbeafe'},unique:{fg:'#b91c1c',bg:'#fee2e2'}};

function canvasWrapV78(ctx,text,maxWidth){let words=safeText(text).replace(/\s+/g,' ').trim().split(' '),lines=[],line='';words.forEach(w=>{let test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test});if(line)lines.push(line);return lines.length?lines:['']}

function roundRectV78(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}

function drawPillV78(ctx,text,x,y,fg,bg){ctx.font='700 24px Arial';let w=ctx.measureText(text).width+28;ctx.fillStyle=bg;roundRectV78(ctx,x-w,y-28,w,38,18);ctx.fill();ctx.fillStyle=fg;ctx.textAlign='right';ctx.fillText(text,x-14,y-2);return w+10}

async function downloadGroupImage(id){let g=findActive(id);if(!g)return;toast('جاري إنشاء الصورة...', 'info');try{let W=1500,pad=70,lineH=54,y=pad,measure=document.createElement('canvas').getContext('2d');measure.font='34px Arial';let maxText=W-pad*2,totalLines=3;(g.verses||[]).forEach(v=>{totalLines+=1;(v.parts||[]).forEach(p=>totalLines+=canvasWrapV78(measure,p.text,maxText).length)});if(g.note)totalLines+=canvasWrapV78(measure,htmlToPlainText(g.note),maxText).length+2;if(g.unote)totalLines+=canvasWrapV78(measure,htmlToPlainText(g.unote),maxText).length+2;let H=Math.max(900,pad*2+totalLines*lineH+220),scale=2,c=document.createElement('canvas');c.width=W*scale;c.height=H*scale;let ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.direction='rtl';ctx.textBaseline='top';ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#d8dee8';ctx.lineWidth=3;roundRectV78(ctx,24,24,W-48,H-48,34);ctx.stroke();ctx.textAlign='right';ctx.fillStyle='#0f172a';ctx.font='800 42px Arial';canvasWrapV78(ctx,g.title||'بدون عنوان',maxText).forEach(line=>{ctx.fillText(line,W-pad,y);y+=58});y+=10;let x=W-pad;x-=drawPillV78(ctx,'مجموعة '+safeText(g.id),x,y,'#1d4ed8','#dbeafe');getTags(g).forEach(s=>{x-=drawPillV78(ctx,'#'+s,x,y,groupHasUniqueInSurah(g,s)?'#991b1b':'#334155',groupHasUniqueInSurah(g,s)?'#fee2e2':'#f1f5f9')});y+=60;(g.verses||[]).forEach((v,idx)=>{ctx.fillStyle='#475569';ctx.font='800 27px Arial';ctx.fillText(`${idx+1}. سورة ${safeText(v.surah)} — آية ${safeText(v.ayah)}${v.label?' — '+safeText(v.label):''}`,W-pad,y);y+=46;(v.parts||[]).forEach(p=>{let st=SHARE_COLORS_V78[p.type||'normal']||SHARE_COLORS_V78.normal;ctx.font='34px Arial';canvasWrapV78(ctx,p.text,maxText).forEach(line=>{let tw=ctx.measureText(line).width;if(st.bg){ctx.fillStyle=st.bg;roundRectV78(ctx,W-pad-tw-16,y-4,tw+24,44,10);ctx.fill()}ctx.fillStyle=st.fg;ctx.fillText(line,W-pad,y);y+=52})});y+=24});function drawNote(title,text,bg,fg){if(!text)return;ctx.fillStyle=bg;roundRectV78(ctx,pad,y,W-pad*2,58,16);ctx.fill();ctx.fillStyle=fg;ctx.font='800 28px Arial';ctx.fillText(title,W-pad-18,y+13);y+=74;ctx.fillStyle='#0f172a';ctx.font='30px Arial';canvasWrapV78(ctx,htmlToPlainText(text),maxText).forEach(line=>{ctx.fillText(line,W-pad,y);y+=48});y+=24}drawNote('ملاحظة',g.note,'#eff6ff','#1d4ed8');drawNote('فائدة إضافية',g.unote,'#fff1f2','#b91c1c');c.toBlob(async blob=>{if(!blob){toast('فشل إنشاء الصورة','err');return}let file=new File([blob],`mutashabihat_group_${safeText(g.id)}_HD.png`,{type:'image/png'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:g.title||'متشابهات'});toast('تم تجهيز الصورة للمشاركة','ok');return}}catch(e){}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1600);toast('تم تنزيل الصورة HD','ok')},'image/png',1)}catch(e){console.error(e);toast('فشل إنشاء الصورة','err')}}
