window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[102] = [];
window.AUTOMATED_SURAH_DATA["التكاثر"] = window.AUTOMATED_SURAH_DATA_BY_NO[102];
