window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[113] = [];
window.AUTOMATED_SURAH_DATA["الفلق"] = window.AUTOMATED_SURAH_DATA_BY_NO[113];
