window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[110] = [];
window.AUTOMATED_SURAH_DATA["النصر"] = window.AUTOMATED_SURAH_DATA_BY_NO[110];
