window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[99] = [];
window.AUTOMATED_SURAH_DATA["الزلزلة"] = window.AUTOMATED_SURAH_DATA_BY_NO[99];
