'use client'
import type { Dashboard,QuestionType } from '@/lib/quiz/types'
import { QUESTION_LABELS,QUIZ_CONFIG } from '@/lib/quiz/config'
import { CategoryTable } from './QuizResults'
import { LEVEL_LABELS,MODE_LABELS,seconds } from './labels'
import s from './quiz.module.css'
export default function QuizDashboard({data,surahs,onOpen,hasMore,onMore,busy}:{data:Dashboard;surahs:Record<string,string>;onOpen:(id:string)=>void;hasMore:boolean;onMore:()=>void;busy:boolean}) {
 const rankedTypes=data.byType.filter(t=>t.attempts>=QUIZ_CONFIG.minimumAttempts).sort((a,b)=>b.accuracy-a.accuracy)
 const rankedSurahs=data.bySurah.filter(t=>t.attempts>=QUIZ_CONFIG.minimumAttempts).sort((a,b)=>b.accuracy-a.accuracy)
 return <div className={s.stack}><section className={`${s.card} ${s.stack}`}><h2>رحلة الحفظ</h2><div className={s.stats}>{[[data.totalQuizzes,'اختبارات مكتملة'],[data.totalQuestions,'إجابات محفوظة'],[`${data.accuracy}%`,'الدقة العامة'],[`${data.recentAccuracy}%`,'دقة آخر ١٠٠ إجابة'],[data.mutashabihatAccuracy===null?'—':`${data.mutashabihatAccuracy}%`,'دقة المتشابهات'],[data.transitionAccuracy===null?'—':`${data.transitionAccuracy}%`,'دقة الانتقال']].map(([v,label])=><div className={s.stat} key={String(label)}><strong>{v}</strong><span>{label}</span></div>)}</div>
 {data.totalQuestions===0&&<p className={s.muted}>ابدأ أول اختبار لتظهر إحصاءاتك ونقاط المراجعة.</p>}
 {rankedTypes.length>1&&<p className={s.muted}>أقوى نوع: {QUESTION_LABELS[rankedTypes[0].key as QuestionType]} ({rankedTypes[0].accuracy}%) · الأكثر حاجة للمراجعة: {QUESTION_LABELS[rankedTypes[rankedTypes.length-1].key as QuestionType]} ({rankedTypes[rankedTypes.length-1].accuracy}%)</p>}
 {data.byType.length>0&&<details className={s.details}><summary>تفصيل الأداء</summary><CategoryTable stats={data.byType} label={k=>QUESTION_LABELS[k as QuestionType]}/>{rankedSurahs.length>0&&<><h3>السور — خمس إجابات على الأقل</h3><CategoryTable stats={rankedSurahs} label={k=>surahs[k]??k}/></>}</details>}
 {data.trend.length>0&&<details className={s.details}><summary>التقدّم خلال ٣٠ يومًا</summary><div className={s.trend} aria-hidden>{data.trend.map(t=><div key={t.date} className={s.trendBar} style={{height:`${Math.max(4,t.accuracy)}px`}} title={`${t.date}: ${t.accuracy}% (${t.attempts})`}/>)}</div><table className={s.table}><thead><tr><th>التاريخ</th><th>الإجابات</th><th>الدقة</th></tr></thead><tbody>{data.trend.map(t=><tr key={t.date}><td>{t.date}</td><td>{t.attempts}</td><td>{t.accuracy}%</td></tr>)}</tbody></table></details>}
 </section><section className={s.stack}><h2>سجل الاختبارات</h2>{!data.sessions.length&&<p className={s.muted}>سيظهر اختبارك الأول هنا، ويمكنك استكماله أو مراجعة أخطائه في أي وقت.</p>}<div className={s.history}>{data.sessions.map(item=><button key={item.id} className={s.historyItem} onClick={()=>onOpen(item.id)}><span><strong>{MODE_LABELS[item.settings.mode]}</strong><span className={s.muted} style={{display:'block'}}>{new Date(item.startedAt).toLocaleDateString('ar',{year:'numeric',month:'short',day:'numeric'})} · {LEVEL_LABELS[item.settings.difficulty]} · {item.questionCount} سؤالًا · {seconds(item.durationSeconds)}</span></span><span>{item.completedAt?`${item.correct} / ${item.questionCount}`:`استكمال ${item.answered} / ${item.questionCount}`}</span></button>)}</div>{hasMore&&<button className={s.secondary} disabled={busy} onClick={onMore}>عرض المزيد</button>}</section></div>
}
