window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[111] = [];
window.AUTOMATED_SURAH_DATA["المسد"] = window.AUTOMATED_SURAH_DATA_BY_NO[111];
