-- Phase 4: a change stores a whole annotation aggregate, never an unsafe partial row.
CREATE TABLE IF NOT EXISTS qiraat_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),batch_key text UNIQUE NOT NULL,status text NOT NULL DEFAULT 'candidate' CHECK(status IN('candidate','preview','selected','applied','validated','committed','rolled_back','failed')),entry_method text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),committed_at timestamptz,rolled_back_at timestamptz);
CREATE TABLE IF NOT EXISTS qiraat_batch_changes (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,batch_id uuid NOT NULL REFERENCES qiraat_batches(id) ON DELETE CASCADE,operation text NOT NULL CHECK(operation IN('INSERT','UPDATE','DELETE')),entity_type text NOT NULL DEFAULT 'annotation_aggregate',record_id uuid NOT NULL,before_json jsonb,after_json jsonb,sequence_number integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(batch_id,sequence_number));
CREATE OR REPLACE FUNCTION qiraat_restore_annotation_snapshot(s jsonb) RETURNS void LANGUAGE plpgsql AS $$ DECLARE x jsonb; BEGIN IF s IS NULL THEN RETURN; END IF; IF NOT EXISTS(SELECT 1 FROM qiraat_annotations WHERE id=(s->'annotation'->>'id')::uuid) THEN INSERT INTO qiraat_annotations SELECT (jsonb_populate_record(NULL::qiraat_annotations,s->'annotation')).*; END IF; FOR x IN SELECT value FROM jsonb_array_elements(coalesce(s->'faces','[]')) LOOP INSERT INTO qiraat_annotation_faces SELECT (jsonb_populate_record(NULL::qiraat_annotation_faces,x)).*; END LOOP; FOR x IN SELECT value FROM jsonb_array_elements(coalesce(s->'variants','[]')) LOOP INSERT INTO qiraat_annotation_variants SELECT (jsonb_populate_record(NULL::qiraat_annotation_variants,x)).*; END LOOP; FOR x IN SELECT value FROM jsonb_array_elements(coalesce(s->'sources','[]')) LOOP INSERT INTO qiraat_annotation_sources SELECT (jsonb_populate_record(NULL::qiraat_annotation_sources,x)).*; END LOOP; END $$;
CREATE OR REPLACE FUNCTION rollback_qiraat_batch(b uuid) RETURNS void LANGUAGE plpgsql AS $$ DECLARE c qiraat_batch_changes; s jsonb; BEGIN IF EXISTS(SELECT 1 FROM qiraat_batches WHERE id=b AND status='rolled_back') THEN RETURN; END IF; IF NOT EXISTS(SELECT 1 FROM qiraat_batches WHERE id=b AND status IN('applied','validated','committed')) THEN RAISE EXCEPTION 'batch is not rollback eligible'; END IF; FOR c IN SELECT * FROM qiraat_batch_changes WHERE batch_id=b ORDER BY sequence_number DESC LOOP IF c.entity_type<>'annotation_aggregate' THEN RAISE EXCEPTION 'unsupported entity type'; END IF; IF c.operation<>'INSERT' AND (SELECT version FROM qiraat_annotations WHERE id=c.record_id) <> ((c.after_json->'annotation'->>'version')::integer) THEN RAISE EXCEPTION 'ROLLBACK_CONFLICT annotation %',c.record_id; END IF; IF c.operation='INSERT' THEN UPDATE qiraat_annotations SET deleted_at=now(),notes=coalesce(notes,'')||' [batch rollback]' WHERE id=c.record_id; ELSE s:=c.before_json; UPDATE qiraat_annotations SET scope_type=s->'annotation'->>'scope_type',start_word_id=(s->'annotation'->>'start_word_id')::uuid,end_word_id=(s->'annotation'->>'end_word_id')::uuid,taxonomy_id=(s->'annotation'->>'taxonomy_id')::uuid,target_authority_id=s->'annotation'->>'target_authority_id',reading_context=s->'annotation'->>'reading_context',inheritance_action=s->'annotation'->>'inheritance_action',applies_to_descendants=(s->'annotation'->>'applies_to_descendants')::boolean,status=s->'annotation'->>'status',color_override=s->'annotation'->>'color_override',notes=s->'annotation'->>'notes',deleted_at=(s->'annotation'->>'deleted_at')::timestamptz WHERE id=c.record_id; DELETE FROM qiraat_annotation_sources WHERE annotation_id=c.record_id; DELETE FROM qiraat_annotation_variants WHERE annotation_id=c.record_id; DELETE FROM qiraat_annotation_faces WHERE annotation_id=c.record_id; PERFORM qiraat_restore_annotation_snapshot(s); END IF; END LOOP; UPDATE qiraat_batches SET status='rolled_back',rolled_back_at=now() WHERE id=b; END $$;

ALTER TABLE qiraat_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE qiraat_batch_changes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS qiraat_batches_read_all ON qiraat_batches;
DROP POLICY IF EXISTS qiraat_batch_changes_read_all ON qiraat_batch_changes;
CREATE POLICY qiraat_batches_read_all ON qiraat_batches FOR SELECT USING (true);
CREATE POLICY qiraat_batch_changes_read_all ON qiraat_batch_changes FOR SELECT USING (true);
GRANT SELECT ON qiraat_batches,qiraat_batch_changes TO authenticated,service_role;
