-- ############################################################################
-- ##  SUPERSEDED 2026-09-17 — DO NOT APPLY THIS FILE.
-- ##
-- ##  Replaced by 20260917120000_qiraat_v2_schema.sql, which was reviewed against the
-- ##  full 20-page source extraction and executed against a real PostgreSQL 16.
-- ##  This file was never applied to any backend, so nothing depends on it.
-- ##
-- ##  Why it was replaced (see docs/qiraat/10-v2-architecture-plan.md):
-- ##    - no token anchor on page-table rules (الأصول), ~15 of 17 of which are word-anchored;
-- ##    - no locus/variant split, so two أوجه of one word could disagree about their span;
-- ##    - no multi-ayah span, making الإدغام الكبير across an ayah boundary unrepresentable;
-- ##    - no الشواهد, notes, QA-flag or global-أصول tables;
-- ##    - separate reader/narrator tables, unable to hold a source row that mixes both levels.
-- ##
-- ##  2026-09-20: this file's executable SQL was REMOVED. Confirmed live (running the whole
-- ##  supabase/migrations/ folder through a fresh local Supabase CLI stack — `supabase start`
-- ##  applies every *.sql file here in filename order, comments included but never obeyed):
-- ##  this file's `CREATE TYPE qiraat_verification_status AS ENUM ('EXTRACTED', 'MAPPED',
-- ##  'REVIEWED', 'VERIFIED', 'PUBLISHED')` runs BEFORE 20260917120000_qiraat_v2_schema.sql's
-- ##  own `CREATE TYPE qiraat_verification_status` (7 values, including NEEDS_MANUAL_REVIEW and
-- ##  REJECTED) — and that statement is wrapped in `EXCEPTION WHEN duplicate_object THEN NULL`
-- ##  specifically so the V2 migration can be re-applied idempotently. The two banners cancelled
-- ##  each other out silently: the V2 migration's own type declaration was swallowed as "already
-- ##  exists", leaving the real database stuck on this file's 5-value enum forever, unable to
-- ##  ever store NEEDS_MANUAL_REVIEW or REJECTED — a bug this project's own "SUPERSEDED, never
-- ##  applied" banner did not stop, because a comment is not something `psql`/`supabase start`
-- ##  reads before executing. Kept as a zero-length, no-op file (this banner only) rather than
-- ##  deleted, so every existing doc reference to this exact path keeps resolving and git history
-- ##  still holds the original 265-line content for anyone who needs it.
-- ############################################################################
