window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[93] = [];
window.AUTOMATED_SURAH_DATA["الضحى"] = window.AUTOMATED_SURAH_DATA_BY_NO[93];
