window.AUTOMATED_SURAH_DATA_BY_NO = window.AUTOMATED_SURAH_DATA_BY_NO || {};
window.AUTOMATED_SURAH_DATA = window.AUTOMATED_SURAH_DATA || {};
window.AUTOMATED_SURAH_DATA_BY_NO[114] = [];
window.AUTOMATED_SURAH_DATA["الناس"] = window.AUTOMATED_SURAH_DATA_BY_NO[114];
