
/* V78 clean V71 rebuild with restored V72/V73 features */
const PERSONAL_KEY='mutashabihat_v69_personal_db';
const AUTO_KEY='mutashabihat_v69_auto_db';
const SETTINGS_KEY='mutashabihat_v69_settings';
let personalData=[], automatedData=[], activeDb=null, activeData=[];
let draftVerses=[], editGroupId=null, editVersesBuffer=[], selectedSurahFilter=null;
let editMode=localStorage.getItem('mutashabihat_v69_edit_mode')==='true';
let displayMode=localStorage.getItem('mutashabihat_v69_display_mode')||'original';
let editQuranSelectionMode='full';
let onlyWithResults=true, surahRange='all', advancedFilters={status:'all',kind:'',minScore:'',surah:''};
function safeText(v){return v===undefined||v===null?'':String(v)}
function escapeHtml(v){return safeText(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function normalize(v){return safeText(v).toLowerCase().replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[إأآٱا]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ـ/g,'').replace(/\s+/g,' ').trim()}

function normalizeQuranSearchText(v){return safeText(v).toLowerCase()
  .replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,'')
  .replace(/[إأآٱا]/g,'ا').replace(/[ؤ]/g,'و').replace(/[ئ]/g,'ي')
  .replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/\s+/g,' ').trim()}
function getSelectedTextareaText(id){let el=document.getElementById(id);if(!el)return '';let a=el.selectionStart||0,b=el.selectionEnd||0;return (a!==b)?el.value.substring(a,b):''}
function addQuranVerseObject(target, surah, ayah, text, type){let obj={surah:safeText(surah),ayah:safeText(ayah),label:'',parts:[{type:type||'shared',text:safeText(text)}]};if(target==='edit'){editVersesBuffer.push(obj);renderEditVerses();setTimeout(()=>document.getElementById('editVerses')?.lastElementChild?.scrollIntoView({behavior:'smooth',block:'center'}),50)}else{draftVerses.push(obj);renderDraft()}}
function removeQuranVerseObject(target, surah, ayah){let arr=target==='edit'?editVersesBuffer:draftVerses;let idx=arr.findIndex(v=>safeText(v.surah)===safeText(surah)&&safeText(v.ayah)===safeText(ayah));if(idx>=0){arr.splice(idx,1);target==='edit'?renderEditVerses():renderDraft();return true}return false}
function quranItemExists(target, surah, ayah){let arr=target==='edit'?editVersesBuffer:draftVerses;return arr.some(v=>safeText(v.surah)===safeText(surah)&&safeText(v.ayah)===safeText(ayah))}
function quranResultText(prefix, i, fullText){let sel=getSelectedTextareaText(prefix+'QText_'+i);return sel||safeText(fullText)}

function clone(v){return JSON.parse(JSON.stringify(v||[]))}function isTrue(v){return v===true||v==='true'||v===1||v==='1'}
function filePersonal(){return Array.isArray(window.PERSONAL_DATA)?window.PERSONAL_DATA:[]}function fileAuto(){return Array.isArray(window.AUTOMATED_DATA)?window.AUTOMATED_DATA:[]}
function loadDb(k,f){try{let s=JSON.parse(localStorage.getItem(k)||'null');if(Array.isArray(s)&&s.length)return s}catch(e){}return clone(f)}
function saveDb(w){localStorage.setItem(w==='personal'?PERSONAL_KEY:AUTO_KEY,JSON.stringify(w==='personal'?personalData:automatedData));storage('✓ محفوظ')}
function storage(t){let b=document.getElementById('storageBadge');if(b)b.textContent=t}
function init(){applySettings();personalData=loadDb(PERSONAL_KEY,filePersonal());automatedData=loadDb(AUTO_KEY,fileAuto());updateHomeCounts();document.getElementById('displayMode').value=displayMode;openHome();buildSurahFilter();storage('✓ V78 جاهز')}
window.addEventListener('DOMContentLoaded',init);
function resetDualDbCacheV68(){if(confirm('مسح كاش V70 وإعادة التحميل من الملفات؟')){localStorage.removeItem(PERSONAL_KEY);localStorage.removeItem(AUTO_KEY);location.reload()}}
function openHome(){document.getElementById('home').classList.remove('hidden');document.getElementById('workspace').classList.add('hidden');activeDb=null;updateHomeCounts()}
function updateHomeCounts(){let p=document.getElementById('personalCountHome'),a=document.getElementById('autoCountHome');if(p)p.textContent=personalData.length+' مجموعة';if(a)a.textContent=automatedData.length+' مجموعة'}
function openDatabase(w){activeDb=w;activeData=w==='personal'?personalData:automatedData;document.getElementById('home').classList.add('hidden');document.getElementById('workspace').classList.remove('hidden');document.getElementById('dbTitle').textContent=w==='personal'?'المتشابهات الشخصية':'المتشابهات الآلية';document.getElementById('dbSubTitle').textContent=w==='personal'?'قابلة للإضافة والتعديل والحذف':'للمراجعة والنسخ للشخصية فقط';renderActiveGroups();buildSurahFilter()}
function setDisplayMode(v){displayMode=v;localStorage.setItem('mutashabihat_v69_display_mode',v);renderActiveGroups()}
function clearSearch(){document.getElementById('searchInput').value='';renderActiveGroups()}
function surahNames(){return typeof SURAH_NAMES!=='undefined'?SURAH_NAMES:{1:'الفاتحة',2:'البقرة',3:'آل عمران',4:'النساء',5:'المائدة',6:'الأنعام',7:'الأعراف',8:'الأنفال',9:'التوبة',10:'يونس',11:'هود',12:'يوسف',13:'الرعد',14:'إبراهيم',15:'الحجر',16:'النحل',17:'الإسراء',18:'الكهف',19:'مريم',20:'طه',21:'الأنبياء',22:'الحج',23:'المؤمنون',24:'النور',25:'الفرقان',26:'الشعراء',27:'النمل',28:'القصص',29:'العنكبوت',30:'الروم',31:'لقمان',32:'السجدة',33:'الأحزاب',34:'سبأ',35:'فاطر',36:'يس',37:'الصافات',38:'ص',39:'الزمر',40:'غافر',41:'فصلت',42:'الشورى',43:'الزخرف',44:'الدخان',45:'الجاثية',46:'الأحقاف',47:'محمد',48:'الفتح',49:'الحجرات',50:'ق',51:'الذاريات',52:'الطور',53:'النجم',54:'القمر',55:'الرحمن',56:'الواقعة',57:'الحديد',58:'المجادلة',59:'الحشر',60:'الممتحنة',61:'الصف',62:'الجمعة',63:'المنافقون',64:'التغابن',65:'الطلاق',66:'التحريم',67:'الملك',68:'القلم',69:'الحاقة',70:'المعارج',71:'نوح',72:'الجن',73:'المزمل',74:'المدثر',75:'القيامة',76:'الإنسان',77:'المرسلات',78:'النبأ',79:'النازعات',80:'عبس',81:'التكوير',82:'الانفطار',83:'المطففين',84:'الانشقاق',85:'البروج',86:'الطارق',87:'الأعلى',88:'الغاشية',89:'الفجر',90:'البلد',91:'الشمس',92:'الليل',93:'الضحى',94:'الشرح',95:'التين',96:'العلق',97:'القدر',98:'البينة',99:'الزلزلة',100:'العاديات',101:'القارعة',102:'التكاثر',103:'العصر',104:'الهمزة',105:'الفيل',106:'قريش',107:'الماعون',108:'الكوثر',109:'الكافرون',110:'النصر',111:'المسد',112:'الإخلاص',113:'الفلق',114:'الناس'}}
function getSurahNo(n){let names=surahNames();for(let no in names)if(normalize(names[no])===normalize(n))return Number(no);return 9999}
function getTags(g){let a=Array.isArray(g.surahs)?g.surahs.filter(Boolean):[];if(!a.length&&Array.isArray(g.verses))a=[...new Set(g.verses.map(v=>v.surah).filter(Boolean))];return a}
function groupText(g){return [g.title,g.note,g.unote,g.candidateKind,g.candidateScore,g.sharedPhrase,...getTags(g),...(g.verses||[]).flatMap(v=>[v.surah,v.ayah,v.label,...(v.parts||[]).map(p=>p.text)])].join(' ')}
function passStatus(g,s){s=s||'all';if(s==='favorite')return isTrue(g.favorite);if(s==='completed')return isTrue(g.completed);if(s==='notCompleted')return !isTrue(g.completed);if(s==='locked')return isTrue(g.locked);if(s==='autoCandidate')return isTrue(g.autoCandidate);return true}
function passFilters(g){let q=normalize(document.getElementById('searchInput')?.value||'');let st=document.getElementById('statusFilter')?.value||'all';if(q&&!normalize(groupText(g)).includes(q))return false;if(!passStatus(g,st)||!passStatus(g,advancedFilters.status))return false;if(selectedSurahFilter&&!getTags(g).includes(selectedSurahFilter))return false;if(advancedFilters.kind&&safeText(g.candidateKind)!==advancedFilters.kind)return false;if(advancedFilters.minScore&&Number(g.candidateScore||0)<Number(advancedFilters.minScore))return false;if(advancedFilters.surah&&!getTags(g).some(s=>normalize(s).includes(normalize(advancedFilters.surah))))return false;return true}
function sortGroups(a){a=a.slice();let fs=g=>Math.min(...getTags(g).map(getSurahNo),9999),fa=g=>Math.min(...(g.verses||[]).map(v=>Number(v.ayah)||9999),9999);if(displayMode==='sort-surah'||displayMode==='group-surah')a.sort((x,y)=>fs(x)-fs(y)||fa(x)-fa(y)||(Number(x.id)||0)-(Number(y.id)||0));if(displayMode==='newest')a.sort((x,y)=>(Number(y.id)||0)-(Number(x.id)||0));if(displayMode==='most-verses')a.sort((x,y)=>(y.verses||[]).length-(x.verses||[]).length);return a}
function renderActiveGroups(){if(!activeDb)return;let list=sortGroups(activeData.filter(passFilters));document.getElementById('counter').textContent='عدد النتائج: '+list.length;renderChips(list.length);renderSurahIndex(list);document.getElementById('groups').innerHTML=list.length?(displayMode==='group-surah'?renderGrouped(list):list.map(renderCard).join('')):'<div class="hint">لا توجد نتائج</div>';updateToggleAllButton();buildSurahFilter()}
function renderChips(c){let chips=['المعروض: '+c];if(selectedSurahFilter)chips.push('السورة: '+selectedSurahFilter);if(advancedFilters.kind)chips.push('النوع: '+advancedFilters.kind);document.getElementById('activeFilterChips').innerHTML=chips.map(x=>`<span>${escapeHtml(x)}</span>`).join('')}
function renderSurahIndex(list){let bar=document.getElementById('surahIndexBar');if(displayMode!=='group-surah'){bar.innerHTML='';return}let m=new Map();list.forEach(g=>getTags(g).forEach(s=>m.set(s,(m.get(s)||0)+1)));bar.innerHTML=[...m].sort((a,b)=>getSurahNo(a[0])-getSurahNo(b[0])).map(([s,c])=>`<button onclick="document.getElementById('sec-${getSurahNo(s)}')?.scrollIntoView({behavior:'smooth'})">${escapeHtml(s)} (${c})</button>`).join('')}
function renderGrouped(list){let m=new Map();list.forEach(g=>(getTags(g).length?getTags(g):['غير محدد']).forEach(s=>{if(!m.has(s))m.set(s,[]);m.get(s).push(g)}));return [...m].sort((a,b)=>getSurahNo(a[0])-getSurahNo(b[0])).map(([s,items])=>`<section id="sec-${getSurahNo(s)}" class="surah-section"><div class="group-head" onclick="this.parentElement.classList.toggle('collapsed')"><div class="group-num">${getSurahNo(s)===9999?'؟':getSurahNo(s)}</div><div class="group-title-wrap"><div class="group-title">📖 سورة ${escapeHtml(s)}</div><div class="group-tags"><span class="tag">${items.length} مجموعة</span></div></div></div><div class="surah-section-groups">${items.map(renderCard).join('')}</div></section>`).join('')}
function renderCard(g){let fav=isTrue(g.favorite),done=isTrue(g.completed),locked=isTrue(g.locked),ro=activeDb==='auto';let actions=`<button class="icon-btn star ${fav?'active':''}" onclick="event.stopPropagation();toggleFlag(${g.id},'favorite')">★</button><button class="icon-btn done ${done?'active':''}" onclick="event.stopPropagation();toggleFlag(${g.id},'completed')">✓</button>`;if(editMode)actions+=`<button class="icon-btn lock ${locked?'active':''}" onclick="event.stopPropagation();toggleFlag(${g.id},'locked')">🔒</button><button onclick="event.stopPropagation();openCompareModal(${g.id})">مقارنة</button>${ro?`<button onclick="event.stopPropagation();copyAutoGroupToPersonal(${g.id})">نسخ للشخصية</button>`:`<button onclick="event.stopPropagation();openEditModal(${g.id})">✏️ تعديل</button>`}`;let cls=(fav?' is-favorite':'')+(done?' is-completed':'')+(locked?' is-locked':'');return `<article class="group${cls}" data-id="${g.id}"><div class="group-head" onclick="toggleGroup(this)"><div class="group-num">${escapeHtml(g.id)}</div><div class="group-title-wrap"><div class="group-tags">${getTags(g).map(s=>`<span class="tag">#${escapeHtml(s)}</span>`).join('')}<span class="tag">${(g.verses||[]).length} آية</span>${g.candidateScore?`<span class="tag">score ${g.candidateScore}</span>`:''}</div><div class="group-title">${highlight(g.title||'بدون عنوان')}</div></div><div class="group-actions">${actions}<button class="icon-btn" onclick="event.stopPropagation();copyGroupText(${g.id})">⧉</button></div></div><div class="group-body">${(g.verses||[]).map(renderVerse).join('')}${g.note?`<div class="note">${safeRich(g.note)}</div>`:''}${g.unote?`<div class="unote">${safeRich(g.unote)}</div>`:''}</div></article>`}
function renderVerse(v){return `<div class="verse-card"><div class="verse-ref"><span class="surah-name">${escapeHtml(v.surah)}</span><span class="ayah-num">${escapeHtml(v.ayah)}</span>${v.label?`<span class="verse-label">${escapeHtml(v.label)}</span>`:''}</div><div class="verse-text">${(v.parts||[]).map(p=>`<span class="${escapeHtml(p.type||'normal')}">${highlight(p.text)}</span>`).join(' ')}</div></div>`}
function safeRich(v){let s=safeText(v);return /<\/?(b|strong|u|span|br|div|p|ul|ol|li)/i.test(s)?s.replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi,''):escapeHtml(s).replace(/\n/g,'<br>')}
function highlight(t){let q=safeText(document.getElementById('searchInput')?.value).trim();let s=escapeHtml(t);if(!q)return s;return s.replace(new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'),m=>`<mark>${m}</mark>`)}
function toggleGroup(h){h.parentElement.classList.toggle('open');updateToggleAllButton()}function toggleAllGroups(){let gs=[...document.querySelectorAll('.group')],all=gs.length&&gs.every(g=>g.classList.contains('open'));gs.forEach(g=>g.classList.toggle('open',!all));updateToggleAllButton()}function updateToggleAllButton(){let b=document.getElementById('toggleAllBtn'),gs=[...document.querySelectorAll('.group')];if(b)b.textContent=gs.length&&gs.every(g=>g.classList.contains('open'))?'طي الكل':'فتح الكل'}
function findActive(id){return activeData.find(g=>Number(g.id)===Number(id))}function toggleFlag(id,f){let g=findActive(id);if(!g)return;g[f]=!isTrue(g[f]);saveDb(activeDb);renderActiveGroups();updateHomeCounts()}function nextPersonalId(){return Math.max(0,...personalData.map(g=>Number(g.id)||0))+1}function copyAutoGroupToPersonal(id){let g=automatedData.find(x=>Number(x.id)===Number(id));if(!g)return;let c=clone([g])[0];c.id=nextPersonalId();c.autoCandidate=false;c.source='automated';personalData.push(c);saveDb('personal');alert('تم النسخ إلى الشخصية');updateHomeCounts()}function copyGroupText(id){let g=findActive(id);if(!g)return;let txt=`${g.title}\n`+(g.verses||[]).map(v=>`${v.surah} ${v.ayah}: ${(v.parts||[]).map(p=>p.text).join('')}`).join('\n');navigator.clipboard?.writeText(txt);alert('تم النسخ')}
function surahCounts(data=activeData){let m={};(data||[]).forEach(g=>getTags(g).forEach(s=>m[s]=(m[s]||0)+1));return m}function buildSurahFilter(){renderSurahFilter()}function rangeBounds(){if(surahRange==='1-30')return[1,30];if(surahRange==='31-60')return[31,60];if(surahRange==='61-90')return[61,90];if(surahRange==='91-114')return[91,114];return[1,114]}function toggleSurahFilterPanel(){let p=document.getElementById('surahFilterPanel'),b=document.getElementById('surahFilterToggleBtn');p.classList.toggle('hidden');b.textContent=p.classList.contains('hidden')?'فتح الفلتر ▾':'إغلاق الفلتر ▴'}function toggleOnlyWithResults(){onlyWithResults=!onlyWithResults;document.getElementById('onlyResultsBtn').classList.toggle('active',onlyWithResults);renderSurahFilter()}function setSurahRange(r){surahRange=r;document.querySelectorAll('.range-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.range===r));renderSurahFilter()}function filterBySurah(s){selectedSurahFilter=s;document.getElementById('filterStatus').textContent='المعروض الآن: '+s;renderActiveGroups()}function clearSurahFilter(){selectedSurahFilter=null;document.getElementById('filterStatus').textContent='المعروض الآن: كل السور';renderActiveGroups()}function renderSurahFilter(){let grid=document.getElementById('surahFilterGrid'),top=document.getElementById('topSurahGrid');if(!grid)return;let names=surahNames(),counts=surahCounts(activeData.length?activeData:personalData),q=normalize(document.getElementById('surahFilterSearch')?.value||''),[a,b]=rangeBounds();let items=Object.keys(names).map(no=>({no:+no,name:names[no],count:counts[names[no]]||0}));let visible=items.filter(i=>i.no>=a&&i.no<=b&&(!onlyWithResults||i.count>0||i.name===selectedSurahFilter)&&(!q||String(i.no).includes(q)||normalize(i.name).includes(q)));grid.innerHTML=visible.map(pill).join('')||'<div class="hint">لا توجد سور مطابقة</div>';top.innerHTML=items.filter(i=>i.count>0).sort((x,y)=>y.count-x.count).slice(0,8).map(pill).join('');document.getElementById('surahCountLine').textContent=`كل السور المعروض: ${visible.length} من 114 سورة`}function pill(i){return `<button class="surah-pill ${selectedSurahFilter===i.name?'active':''} ${!i.count?'no-match':''}" onclick="filterBySurah('${i.name}')"><span class="no-badge">${i.no}</span><span>${i.name}</span><span class="count-badge">${i.count}</span></button>`}
function partOptions(sel){return ['normal','shared','diff','diff2','addition','unique'].map(x=>`<option value="${x}" ${x===sel?'selected':''}>${x}</option>`).join('')}function qAyahs(){let arr=[];try{for(let s=1;s<=114;s++)(getSurahAyahs(s)||[]).forEach(a=>arr.push(a))}catch(e){}return arr}function getRef(no,ay){try{return typeof getAyah==='function'?getAyah(no,ay):null}catch(e){return null}}
function openAddModal(){if(activeDb==='auto'){alert('الإضافة في الشخصية فقط');openDatabase('personal')}draftVerses=[];modal('addModal','إضافة متشابه جديد',addBody(),`<button class="primary" onclick="createNewGroup()">حفظ في الصفحة</button><button onclick="closeModal('addModal')">إغلاق</button>`);populateSurah('addSurah');onAddSurah();renderDraft();runQuranSearch('add')}
function addBody(){return `<div class="quran-search-box"><div class="search-stats"><span id="addExact">0 :Exact</span><span id="addClose">0 :Close</span><span id="addTotal">0 :Total</span></div><h3>بحث في quran-reference.js</h3><p>بحث ذكي يتجاهل التشكيل واختلافات الحروف. النتائج المطابقة حرفياً أولاً ثم القريبة.</p><input class="wide-input" id="addQSearch" placeholder="اكتب كلمة أو جزء من آية..." oninput="runQuranSearch('add')"><div id="addQResults" class="quran-results hint">اكتب كلمة لعرض النتائج.</div></div><label class="field">عنوان المتشابه<input id="addTitle" placeholder="مثال: الرجفة / الصيحة"></label><button onclick="generateTitleFromDraft()">توليد عنوان تلقائي</button><div class="color-row"><b>لون المجموعة</b><input type="color" id="addColor" value="#55b94f" oninput="document.getElementById('addColorPrev').style.background=this.value"><span id="addColorPrev" class="color-preview">معاينة اللون</span></div><div class="form-grid"><label class="field">السورة<select id="addSurah" onchange="onAddSurah()"></select></label><label class="field">رقم الآية<select id="addAyah" onchange="previewAddAyah()"></select></label><label class="field">نوع التلوين<select id="addType">${partOptions('shared')}</select></label><label class="field">وصف قصير للآية / Label<input id="addLabel"></label></div><label class="field">نص الآية من quran-reference.js<textarea id="addPreview" readonly></textarea></label><label class="field">معاينة مباشرة:<div id="addLive" class="live-preview verse-text"></div></label><label class="field">تحديد جزء من الآية فقط<textarea id="addSelectedPart"></textarea></label><div class="inline-actions"><button class="primary" onclick="addVerseToDraft()">إضافة الآية للمجموعة</button><button onclick="clearDraft()">مسح الآيات المؤقتة</button></div><h3>الآيات المؤقتة</h3><div id="draftVerses"></div>${richEditor('addNote','ملاحظة','#1d4ed8')}${richEditor('addUnote','فائدة فريدة / إضافية','#b91c1c')}`}
function richEditor(id,label,color){return `<label class="field">${label}<div class="rt-box"><div class="rt-toolbar"><button onclick="rt('${id}','bold')"><b>B</b></button><button onclick="rt('${id}','underline')"><u>U</u></button><button onclick="rt('${id}','insertUnorderedList')">• قائمة</button><input type="color" value="${color}" onchange="rtColor('${id}',this.value)"><button onclick="rt('${id}','removeFormat')">مسح تنسيق</button></div><div id="${id}" class="rt-editor" contenteditable="true"></div></div></label>`}function rt(id,cmd){let e=document.getElementById(id);e.focus();document.execCommand(cmd,false,null)}function rtColor(id,c){let e=document.getElementById(id);e.focus();document.execCommand('foreColor',false,c)}
function runQuranSearch(prefix){
  let input=document.getElementById(prefix+'QSearch'), q=input?.value.trim()||'', box=document.getElementById(prefix+'QResults');
  if(!box)return;
  ['Exact','Close','Total'].forEach(k=>{let el=document.getElementById(prefix+k);if(el)el.textContent='0 :'+k});
  if(!q){box.className='quran-results hint';box.innerHTML='اكتب كلمة لعرض النتائج.';return}
  let nq=normalizeQuranSearchText(q), exact=[], close=[];
  qAyahs().forEach(a=>{let txt=safeText(a.text), nt=normalizeQuranSearchText(txt); if(txt.includes(q)) exact.push(a); else if(nt.includes(nq)) close.push(a)});
  let total=exact.length+close.length, all=exact.concat(close).slice(0,80);
  let e=document.getElementById(prefix+'Exact'), c=document.getElementById(prefix+'Close'), t=document.getElementById(prefix+'Total');
  if(e)e.textContent=exact.length+' :Exact'; if(c)c.textContent=close.length+' :Close'; if(t)t.textContent=total+' :Total';
  box.className='quran-results';
  box.innerHTML=all.map((a,i)=>{
    let target=prefix==='edit'?'edit':'add', exists=quranItemExists(target,a.surah,a.ayahNo), checked=exists?'checked':'';
    return `<div class="quran-result ${exists?'selected':''}">
      <label class="quran-check-line"><input type="checkbox" class="${prefix}QCheck" ${checked} onchange="toggleQuranResult('${prefix}',this)" data-index="${i}" data-surah-no="${a.surahNo||a.surah}" data-ayah="${a.ayahNo}" data-text="${escapeHtml(a.text)}" data-surah="${escapeHtml(a.surah)}"><span>${exists?'مضاف':'تحديد'}</span></label>
      <div class="quran-result-body"><b>${a.surah} — ${a.ayahNo}</b><textarea id="${prefix}QText_${i}" class="quran-result-text" readonly>${escapeHtml(a.text)}</textarea>
      <div class="quran-result-actions"><button onclick="addFullQuranResult('${prefix}',this)">إضافة الآية كاملة</button><button onclick="addSelectedQuranResult('${prefix}',${i},this)">إضافة النص المحدد</button></div></div>
    </div>`}).join('') + `<div class="quran-result-toolbar"><button class="primary" onclick="addCheckedQuran('${prefix}')">إضافة المحدد</button><small>حدد جزءاً من النص داخل مربع الآية ثم اضغط «إضافة النص المحدد».</small></div>`;
}
function addCheckedQuran(prefix){
  document.querySelectorAll('.'+prefix+'QCheck:checked').forEach(ch=>{let txt=ch.dataset.text;if(!quranItemExists(prefix==='edit'?'edit':'add',ch.dataset.surah,ch.dataset.ayah))addQuranVerseObject(prefix==='edit'?'edit':'add',ch.dataset.surah,ch.dataset.ayah,txt,'shared')});
  if(prefix==='edit')runQuranSearch('edit'); else runQuranSearch('add');
}
function toggleQuranResult(prefix,ch){let target=prefix==='edit'?'edit':'add'; if(ch.checked){if(!quranItemExists(target,ch.dataset.surah,ch.dataset.ayah))addQuranVerseObject(target,ch.dataset.surah,ch.dataset.ayah,ch.dataset.text,'shared')}else{removeQuranVerseObject(target,ch.dataset.surah,ch.dataset.ayah)} runQuranSearch(prefix)}
function addFullQuranResult(prefix,btn){let root=btn.closest('.quran-result'), ch=root?.querySelector('input[type="checkbox"]'); if(!ch)return; addQuranVerseObject(prefix==='edit'?'edit':'add',ch.dataset.surah,ch.dataset.ayah,ch.dataset.text,'shared'); runQuranSearch(prefix)}
function addSelectedQuranResult(prefix,i,btn){let root=btn.closest('.quran-result'), ch=root?.querySelector('input[type="checkbox"]'); if(!ch)return; let txt=quranResultText(prefix,i,ch.dataset.text)||ch.dataset.text; addQuranVerseObject(prefix==='edit'?'edit':'add',ch.dataset.surah,ch.dataset.ayah,txt,'shared'); runQuranSearch(prefix)}
function getValidSurahNo(v){let n=parseInt(v,10);if(n>=1&&n<=114)return n;let g=getSurahNo(v);return g===9999?1:g}
function surahOptionsHtml(sel){let names=surahNames(),selected=getValidSurahNo(sel);return Object.keys(names).map(no=>`<option value="${no}" ${+no===+selected?'selected':''}>${no} - ${names[no]}</option>`).join('')}
function ayahOptionsHtml(no,sel){let arr=[];try{arr=getSurahAyahs(getValidSurahNo(no))||[]}catch(x){};let selected=parseInt(sel,10)||1;return (arr.length?arr:[{ayahNo:1}]).map(a=>`<option value="${a.ayahNo}" ${+a.ayahNo===+selected?'selected':''}>${a.ayahNo}</option>`).join('')}
function populateSurah(id,sel){let e=document.getElementById(id);if(e)e.innerHTML=surahOptionsHtml(sel)}
function populateAyah(id,no,sel){let e=document.getElementById(id);if(e)e.innerHTML=ayahOptionsHtml(no,sel)}
function onAddSurah(){populateAyah('addAyah',document.getElementById('addSurah').value);previewAddAyah()}
function previewAddAyah(){let a=getRef(document.getElementById('addSurah').value,document.getElementById('addAyah').value);let p=document.getElementById('addPreview'),l=document.getElementById('addLive');if(p)p.value=a?a.text:'لم يتم العثور';if(l)l.innerHTML=a?`<span class="${document.getElementById('addType').value}">${escapeHtml(a.text)}</span>`:''}
function addVerseToDraft(){let a=getRef(document.getElementById('addSurah').value,document.getElementById('addAyah').value);if(!a)return alert('لم يتم العثور');draftVerses.push({surah:a.surah,ayah:a.ayahNo,label:document.getElementById('addLabel').value.trim(),parts:[{type:document.getElementById('addType').value,text:document.getElementById('addSelectedPart').value.trim()||a.text}]});renderDraft()}function renderDraft(){let b=document.getElementById('draftVerses');if(!b)return;b.innerHTML=draftVerses.length?draftVerses.map((v,i)=>`<div class="draft-item"><b>${v.surah} ${v.ayah}</b><button class="danger" onclick="draftVerses.splice(${i},1);renderDraft()">حذف</button><div class="verse-text"><span class="${v.parts[0].type}">${escapeHtml(v.parts[0].text)}</span></div></div>`).join(''):'<div class="hint">لا توجد آيات مضافة بعد.</div>'}function clearDraft(){draftVerses=[];renderDraft()}function generateTitleFromDraft(){if(draftVerses.length)document.getElementById('addTitle').value=draftVerses.map(v=>v.surah+' '+v.ayah).join(' / ')}function createNewGroup(){let title=document.getElementById('addTitle').value.trim();if(!title||!draftVerses.length)return alert('أدخل العنوان والآيات');personalData.push({id:nextPersonalId(),title,color:document.getElementById('addColor').value,surahs:[...new Set(draftVerses.map(v=>v.surah))],verses:clone(draftVerses),note:document.getElementById('addNote').innerHTML,unote:document.getElementById('addUnote').innerHTML,favorite:false,completed:false,locked:false});saveDb('personal');closeModal('addModal');openDatabase('personal')}
function openEditModal(id){let g=personalData.find(x=>+x.id===+id);if(!g)return;if(isTrue(g.locked))return alert('المجموعة مقفلة');editGroupId=id;editVersesBuffer=clone(g.verses||[]);modal('editModal','تعديل المتشابه',editBody(g),`<button class="primary" onclick="saveEditGroup()">حفظ التعديل</button><button class="danger" onclick="deleteEditGroup()">حذف المجموعة</button><button onclick="closeModal('editModal')">إغلاق</button>`);renderEditVerses();runQuranSearch('edit')}function editBody(g){return `<div class="quran-search-box edit-quran-search"><div class="search-stats"><span id="editExact">0 :Exact</span><span id="editClose">0 :Close</span><span id="editTotal">0 :Total</span></div><h3>بحث ذكي في القرآن</h3><p>يتجاهل التشكيل واختلافات الهمزات والألف وى/ي وة/ه وؤ/و وئ/ي. النتائج المطابقة أولاً ثم القريبة.</p><input class="wide-input" id="editQSearch" placeholder="ابحث داخل quran-reference.js ثم أضف الآية أو النص المحدد..." oninput="runQuranSearch('edit')"><div id="editQResults" class="quran-results hint">اكتب كلمة لعرض النتائج.</div></div><label class="field">عنوان المتشابه<input id="editTitle" value="${escapeHtml(g.title)}"></label><div class="inline-actions"><button class="primary" onclick="addBlankEditVerse()">+ إضافة آية</button><button onclick="sortEditVersesByMushaf()">ترتيب حسب المصحف</button></div><div id="editVerses"></div>${richEditor('editNote','ملاحظة','#1d4ed8')}${richEditor('editUnote','فائدة فريدة / إضافية','#b91c1c')}`}
function renderEditVerses(){let b=document.getElementById('editVerses');if(!b)return;b.innerHTML=editVersesBuffer.map((v,vi)=>{let sno=getValidSurahNo(v.surah),ayah=v.ayah||1;return `<div class="edit-verse"><div class="edit-verse-title"><b>آية ${vi+1}</b><div><button onclick="moveEditVerse(${vi},-1)">↑</button><button onclick="moveEditVerse(${vi},1)">↓</button><button class="danger" onclick="editVersesBuffer.splice(${vi},1);renderEditVerses()">حذف الآية</button></div></div><div class="form-grid"><label class="field">السورة<select onchange="setEditSurah(${vi},this.value)">${surahOptionsHtml(sno)}</select></label><label class="field">رقم الآية<select onchange="setEditAyah(${vi},this.value)">${ayahOptionsHtml(sno,ayah)}</select></label><label class="field">Label<input value="${escapeHtml(v.label||'')}" onchange="editVersesBuffer[${vi}].label=this.value"></label></div><button onclick="fillEditAyah(${vi})">ملء نص الآية من المرجع</button><h4>أجزاء النص</h4>${(v.parts||[]).map((p,pi)=>partRow(vi,pi,p)).join('')}<button onclick="addEditPart(${vi})">+ إضافة جزء نص</button><div class="live-preview verse-text">${(v.parts||[]).map(p=>`<span class="${p.type}">${escapeHtml(p.text)}</span>`).join(' ')}</div></div>`}).join('')}
function partRow(vi,pi,p){return `<div class="part-row"><select aria-label="نوع الجزء" onchange="editVersesBuffer[${vi}].parts[${pi}].type=this.value;renderEditVerses()">${partOptions(p.type)}</select><textarea aria-label="نص الجزء" onchange="editVersesBuffer[${vi}].parts[${pi}].text=this.value">${escapeHtml(p.text)}</textarea><div class="part-actions"><button title="تحريك لأعلى" onclick="moveEditPart(${vi},${pi},-1)">↑</button><button title="تحريك لأسفل" onclick="moveEditPart(${vi},${pi},1)">↓</button><button title="إضافة قبل" onclick="insertEditPart(${vi},${pi})">+ قبل</button><button title="إضافة بعد" onclick="insertEditPart(${vi},${pi}+1)">+ بعد</button><button class="danger" title="حذف" onclick="removeEditPart(${vi},${pi})">حذف</button></div></div>`}function addBlankEditVerse(){editVersesBuffer.push({surah:'الفاتحة',ayah:1,label:'',parts:[{type:'normal',text:''}]});renderEditVerses()}function moveEditVerse(i,d){let j=i+d;if(j<0||j>=editVersesBuffer.length)return;[editVersesBuffer[i],editVersesBuffer[j]]=[editVersesBuffer[j],editVersesBuffer[i]];renderEditVerses()}function addEditPart(vi){editVersesBuffer[vi].parts.push({type:'normal',text:''});renderEditVerses()}function insertEditPart(vi,pi){editVersesBuffer[vi].parts.splice(pi+1,0,{type:'normal',text:''});renderEditVerses()}function removeEditPart(vi,pi){editVersesBuffer[vi].parts.splice(pi,1);renderEditVerses()}function moveEditPart(vi,pi,d){let a=editVersesBuffer[vi].parts,j=pi+d;if(j<0||j>=a.length)return;[a[pi],a[j]]=[a[j],a[pi]];renderEditVerses()}function setEditSurah(vi,no){let names=surahNames(),sno=getValidSurahNo(no),arr=[];try{arr=getSurahAyahs(sno)||[]}catch(e){};if(!editVersesBuffer[vi])return;editVersesBuffer[vi].surah=names[sno]||String(no);editVersesBuffer[vi].ayah=(arr[0]&&arr[0].ayahNo)||1;renderEditVerses()}
function setEditAyah(vi,ayah){if(!editVersesBuffer[vi])return;editVersesBuffer[vi].ayah=parseInt(ayah,10)||ayah}
function fillEditAyah(vi){let v=editVersesBuffer[vi],a=getRef(getSurahNo(v.surah),v.ayah);if(!a)return alert('لم يتم العثور');v.surah=a.surah;v.ayah=a.ayahNo;v.parts=[{type:'normal',text:a.text}];renderEditVerses()}function sortEditVersesByMushaf(){editVersesBuffer.sort((a,b)=>getSurahNo(a.surah)-getSurahNo(b.surah)||(+a.ayah||0)-(+b.ayah||0));renderEditVerses()}function saveEditGroup(){let i=personalData.findIndex(g=>+g.id===+editGroupId);if(i<0)return;personalData[i]={...personalData[i],title:document.getElementById('editTitle').value.trim(),verses:clone(editVersesBuffer),surahs:[...new Set(editVersesBuffer.map(v=>v.surah))],note:document.getElementById('editNote').innerHTML,unote:document.getElementById('editUnote').innerHTML};saveDb('personal');closeModal('editModal');renderActiveGroups()}function deleteEditGroup(){if(confirm('حذف المجموعة؟')){personalData=personalData.filter(g=>+g.id!==+editGroupId);saveDb('personal');closeModal('editModal');renderActiveGroups();updateHomeCounts()}}
function openCompareModal(id){let g=findActive(id);if(!g)return;modal('compareModal','المقارنة البصرية — '+escapeHtml(g.title),`<div>${(g.verses||[]).map(v=>`<div class="compare-card"><b>${escapeHtml(v.surah)} آية ${escapeHtml(v.ayah)} ${escapeHtml(v.label||'')}</b><div class="compare-text">${(v.parts||[]).map(p=>`<span class="${p.type==='normal'?'base':p.type==='shared'?'same':'cmpdiff'}">${escapeHtml(p.text)}</span>`).join(' ')}</div></div>`).join('')}</div>`,`<button onclick="closeModal('compareModal')">إغلاق</button>`)}
function openMergeWindow(){modal('mergeWindow','دمج / نقل من الآلية إلى الشخصية',`<div class="tools"><input id="mergeSearch" placeholder="ابحث في الآلية..." oninput="renderMergeList()"><button onclick="selectAllMerge(true)">تحديد المعروض</button><button onclick="selectAllMerge(false)">إلغاء التحديد</button><button class="primary" onclick="copySelectedToPersonal()">نقل المحدد</button></div><div id="mergeList"></div>`,`<button onclick="closeModal('mergeWindow')">إغلاق</button>`);renderMergeList()}function renderMergeList(){let q=normalize(document.getElementById('mergeSearch')?.value||''),list=automatedData.filter(g=>!q||normalize(groupText(g)).includes(q));document.getElementById('mergeList').innerHTML=list.map(g=>`<label class="merge-item"><input type="checkbox" class="merge-check" value="${automatedData.indexOf(g)}"><div><b>${escapeHtml(g.title)}</b><br><small>${getTags(g).join('، ')} — ${(g.verses||[]).length} آيات</small></div><button onclick="copyOneToPersonal(${automatedData.indexOf(g)})">نسخ</button></label>`).join('')||'<div class="hint">لا توجد نتائج</div>'}function selectAllMerge(s){document.querySelectorAll('.merge-check').forEach(x=>x.checked=s)}function copyOneToPersonal(i){let g=clone([automatedData[i]])[0];g.id=nextPersonalId();g.autoCandidate=false;g.source='automated';personalData.push(g);saveDb('personal');updateHomeCounts();alert('تم النسخ')}function copySelectedToPersonal(){let ids=[...document.querySelectorAll('.merge-check:checked')].map(x=>+x.value);ids.forEach(copyOneToPersonal)}
function openDashboard(){let d=activeDb?activeData:personalData.concat(automatedData),ayah=d.reduce((s,g)=>s+(g.verses||[]).length,0),surahs=new Set(d.flatMap(getTags)).size;let cards=[['الشخصية',personalData.length],['الآلية',automatedData.length],['المجموعات',d.length],['الآيات',ayah],['السور',surahs],['المفضلة',d.filter(g=>isTrue(g.favorite)).length],['المكتملة',d.filter(g=>isTrue(g.completed)).length],['المقفلة',d.filter(g=>isTrue(g.locked)).length]];modal('dashboardModal','الإحصائيات',`<div class="dashboard-grid">${cards.map(c=>`<div class="dash-card"><div class="dash-value">${c[1]}</div><div>${c[0]}</div></div>`).join('')}</div>`,`<button onclick="closeModal('dashboardModal')">إغلاق</button>`)}function openAdvancedSearch(){modal('advancedModal','بحث متقدم',`<div class="form-grid"><label class="field">الحالة<select id="advStatus"><option value="all">الكل</option><option value="favorite">المفضلة</option><option value="completed">المكتملة</option><option value="notCompleted">غير مكتملة</option><option value="locked">المقفلة</option><option value="autoCandidate">مرشح آلي</option></select></label><label class="field">نوع المرشح<input id="advKind" placeholder="same-opening / shared-phrase"></label><label class="field">أقل درجة<input id="advScore" type="number"></label><label class="field">السورة<input id="advSurah"></label></div>`,`<button class="primary" onclick="applyAdvancedSearch()">تطبيق</button><button onclick="resetAdvancedSearch()">إعادة ضبط</button><button onclick="closeModal('advancedModal')">إغلاق</button>`);document.getElementById('advStatus').value=advancedFilters.status;document.getElementById('advKind').value=advancedFilters.kind;document.getElementById('advScore').value=advancedFilters.minScore;document.getElementById('advSurah').value=advancedFilters.surah}function applyAdvancedSearch(){advancedFilters={status:document.getElementById('advStatus').value,kind:document.getElementById('advKind').value.trim(),minScore:document.getElementById('advScore').value,surah:document.getElementById('advSurah').value.trim()};closeModal('advancedModal');renderActiveGroups()}function resetAdvancedSearch(){advancedFilters={status:'all',kind:'',minScore:'',surah:''};closeModal('advancedModal');renderActiveGroups()}
function openAppSettings(){let s=getSettings();modal('settingsModal','إعدادات التطبيق',`<div class="settings-section"><h2>GitHub Auto Sync ☁</h2><label class="field">Token<input id="ghToken" type="password" value="${escapeHtml(s.ghToken||'')}"></label><div class="form-grid"><label class="field">Repo<input id="ghRepo" value="${escapeHtml(s.ghRepo||'')}"></label><label class="field">Owner<input id="ghOwner" value="${escapeHtml(s.ghOwner||'')}"></label><label class="field">Path<input id="ghPath" value="${escapeHtml(s.ghPath||'data.js')}"></label><label class="field">Branch<input id="ghBranch" value="${escapeHtml(s.ghBranch||'main')}"></label></div><div class="inline-actions"><button class="primary" onclick="saveSettings()">حفظ</button><button onclick="syncToGitHub()">مزامنة الآن</button></div></div><div class="settings-section"><h2>✏️ Edit Mode / وضع التعديل</h2><p>عند تفعيل وضع التعديل تظهر أيقونات التعديل والمقارنة والنقل والدمج وكشف التكرار.</p><label><input type="checkbox" id="editModeCheck" ${editMode?'checked':''}> تفعيل وضع التعديل</label></div><div class="settings-section"><h2>🎨 Theme / Font</h2><div class="form-grid"><label class="field">Theme<select id="setTheme"><option value="quran-classic">Quran Classic</option><option value="apple-health">Apple Health</option><option value="bevel-night">Bevel Night</option></select></label><label class="field">Font<select id="setFont" onchange="updateFontPreview()"><option value="normal-quran">Normal Quran — للبحث والتعديل والمقارنة</option><option value="mushaf-qpc-v2">Mushaf QPC V2 — للعرض والمراجعة</option><option value="classic-quran">Classic Quran (Legacy)</option><option value="modern-reader">Modern Reader (Legacy)</option><option value="mobile-clear">Mobile Clear (Legacy)</option></select></label></div><div id="fontPreviewBox" class="font-preview-box" data-font-preset="normal-quran"><b>معاينة الخط قبل الحفظ</b><div class="font-preview-ayah">وَزَيَّنَ لَهُمُ الشَّيْطَانُ أَعْمَالَهُمْ فَصَدَّهُمْ عَنِ السَّبِيلِ فَهُمْ لَا يَهْتَدُونَ</div><small id="fontPreviewHint">إذا كان مجلد fonts فارغاً سيظهر الخط الاحتياطي تلقائياً.</small></div></div><div class="inline-actions"><button onclick="openReleaseNotes()">Release Notes</button><button onclick="exportActiveDatabase()">Export data.js</button><button onclick="resetDualDbCacheV68()">Reset Cache</button></div>`,`<button class="primary" onclick="saveSettings()">حفظ</button><button onclick="closeModal('settingsModal')">إغلاق</button>`);document.getElementById('setTheme').value=s.theme;document.getElementById('setFont').value=s.font;updateFontPreview()}
function updateFontPreview(){let f=normalizeFontPreset(document.getElementById('setFont')?.value||getSettings().font),box=document.getElementById('fontPreviewBox'),hint=document.getElementById('fontPreviewHint');if(box)box.setAttribute('data-font-preset',f);if(hint)hint.textContent=f==='mushaf-qpc-v2'?'معاينة Mushaf QPC V2. إذا لم يظهر الاختلاف، ضع qpc-v2.woff2 أو qpc-v2.ttf داخل مجلد fonts.':'معاينة الخط العادي المستخدم للبحث والتعديل والمقارنة.'}
function normalizeFontPreset(v){v=safeText(v||'normal-quran');if(v==='classic-quran'||v==='modern-reader'||v==='mobile-clear')return 'normal-quran';if(v!=='normal-quran'&&v!=='mushaf-qpc-v2')return 'normal-quran';return v}function getSettings(){try{let s={...{theme:'quran-classic',font:'normal-quran',ghPath:'data.js',ghBranch:'main'},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};s.font=normalizeFontPreset(s.font);return s}catch(e){return {theme:'quran-classic',font:'normal-quran',ghPath:'data.js',ghBranch:'main'}}}function applySettings(){let s=getSettings();s.font=normalizeFontPreset(s.font);document.body.setAttribute('data-theme',s.theme);document.body.setAttribute('data-font-preset',s.font);let gh=document.getElementById('ghBadge');if(gh)gh.textContent=s.ghOwner&&s.ghRepo?'☁ GitHub ready':'☁ GitHub: not set'}function saveSettings(){let s={theme:document.getElementById('setTheme')?.value||getSettings().theme,font:normalizeFontPreset(document.getElementById('setFont')?.value||getSettings().font),ghToken:document.getElementById('ghToken')?.value||'',ghRepo:document.getElementById('ghRepo')?.value||'',ghOwner:document.getElementById('ghOwner')?.value||'',ghPath:document.getElementById('ghPath')?.value||'data.js',ghBranch:document.getElementById('ghBranch')?.value||'main'};editMode=!!document.getElementById('editModeCheck')?.checked;localStorage.setItem('mutashabihat_v69_edit_mode',editMode);localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));applySettings();closeModal('settingsModal');if(activeDb)renderActiveGroups()}function syncToGitHub(){alert('تم حفظ إعدادات GitHub. المزامنة الحقيقية تحتاج Token وصلاحية repo، وسيتم تفعيلها عند ربط المستودع.')}
const RELEASE=`V78 — Clean V71 + Restored Features

Implemented:
- Added Normal Quran font mode for search, edit, and comparison screens.
- Added Mushaf QPC V2 display/review mode for beautiful reading in group cards.
- Search result textareas, edit part textareas, edit live preview, and comparison view stay on Normal Quran font for readability and accurate editing.
- Group display/review can use Mushaf QPC V2 via Settings > Font.
- Added CSS font-face references ready for local /fonts files: QPC V2, KFGQPCNastaleeq-Regular, surah-name-v4.
- Updated settings font dropdown with the two clear modes.
- Fixed modification modal header color and X close button to follow the current app theme.

Preserved:
- Personal/Automated database separation.
- Smart Quran search in add/edit windows.
- Inline Surah filter and display mode dropdown.
- Added Surah dropdown and dependent Ayah dropdown in the modification window.
- Added live font preview in Settings before saving.
- Clarified that empty fonts folder is optional; place qpc-v2.woff2 or qpc-v2.ttf only if you have the real file.
- Existing Quran reference APIs and data files.`;function openReleaseNotes(){modal('releaseModal','Release Notes — V70',`<div class="release-content">${escapeHtml(RELEASE)}</div>`,`<button onclick="navigator.clipboard?.writeText(RELEASE)">نسخ</button><button onclick="closeModal('releaseModal')">إغلاق</button>`)}function exportActiveDatabase(){if(!activeDb)return alert('افتح قاعدة أولاً');let vn=activeDb==='personal'?'PERSONAL_DATA':'AUTOMATED_DATA',fn=activeDb==='personal'?'personal-data.js':'automated-data.js',blob=new Blob(['window.'+vn+' = '+JSON.stringify(activeData,null,2)+';\n'],{type:'application/javascript;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=fn;a.click()}function modal(id,title,body,footer){closeModal(id);let e=document.createElement('section');e.id=id;e.className='modal-backdrop';let modalClass='modal '+id+'-window';e.innerHTML=`<div class="${modalClass}" role="dialog" aria-modal="true"><div class="modal-head"><h2>${title}</h2><button class="modal-close-btn" aria-label="إغلاق" onclick="closeModal('${id}')">×</button></div><div class="modal-body">${body}</div><div class="modal-footer">${footer||''}</div></div>`;e.onclick=x=>{if(x.target===e)closeModal(id)};document.getElementById('modalRoot').appendChild(e)}function closeModal(id){document.getElementById(id)?.remove()}function openMobileMenu(){let items=[['الرئيسية','openHome()'],['الشخصية',"openDatabase('personal')"],['الآلية',"openDatabase('auto')"],['إضافة','openAddModal()'],['الإحصائيات','openDashboard()'],['الإعدادات','openAppSettings()'],['بحث متقدم','openAdvancedSearch()'],['دمج','openMergeWindow()'],['Release Notes','openReleaseNotes()']];let e=document.createElement('section');e.id='mobileMenu';e.className='modal-backdrop';e.innerHTML=`<div class="mobile-menu-panel"><button onclick="closeModal('mobileMenu')">× إغلاق</button>${items.map(i=>`<button onclick="closeModal('mobileMenu');${i[1]}">${i[0]}</button>`).join('')}</div>`;document.getElementById('modalRoot').appendChild(e)}

/* =========================
   V78 restored features from V72/V73 on clean V71 base
   ========================= */
const LAST_VIEW_KEY_V78='mutashabihat_v78_last_view';
const LAST_SURAH_KEY_V78='mutashabihat_v78_last_surah';
let __modalScrollY_V78=0;
let __touchStartY_V78=0;
let __touchStartX_V78=0;
let __touchStartedOnHead_V78=false;

function iconSvg(name){
  const common='width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';
  const icons={
    star:`<svg ${common}><path d="M12 3.5l2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17.4 6.6 20.3l1-6.1-4.4-4.3 6.1-.9L12 3.5z"/></svg>`,
    lock:`<svg ${common}><rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/></svg>`,
    copy:`<svg ${common}><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>`,
    camera:`<svg ${common}><path d="M4 8h3l1.6-2h6.8L17 8h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2z"/><circle cx="12" cy="14" r="3.4"/></svg>`,
    edit:`<svg ${common}><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z"/></svg>`,
    compare:`<svg ${common}><path d="M8 7h13"/><path d="M8 17h13"/><path d="M3 7h.01"/><path d="M3 17h.01"/></svg>`
  };
  return icons[name]||'';
}
function toast(msg,type){let t=document.getElementById('v78Toast');if(!t){t=document.createElement('div');t.id='v78Toast';document.body.appendChild(t)}t.className='v78-toast '+(type||'');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),2600)}
function lockBodyScrollV78(){if(document.body.classList.contains('modal-open-v78'))return;__modalScrollY_V78=window.scrollY||document.documentElement.scrollTop||0;document.body.style.top=`-${__modalScrollY_V78}px`;document.body.classList.add('modal-open-v78')}
function unlockBodyScrollV78(){if(document.querySelector('.modal-backdrop'))return;document.body.classList.remove('modal-open-v78');document.body.style.top='';window.scrollTo(0,__modalScrollY_V78||0)}
function modal(id,title,body,footer){closeModal(id);let e=document.createElement('section');e.id=id;e.className='modal-backdrop';let modalClass='modal '+id+'-window';e.innerHTML=`<div class="${modalClass}" role="dialog" aria-modal="true"><div class="modal-head"><span class="modal-drag-handle"></span><h2>${title}</h2><button class="modal-close-btn icon-outline" aria-label="إغلاق" onclick="closeModal('${id}')">×</button></div><div class="modal-body">${body}</div><div class="modal-footer">${footer||''}</div></div>`;e.onclick=x=>{if(x.target===e)closeModal(id)};document.getElementById('modalRoot').appendChild(e);lockBodyScrollV78();enableSwipeToClose(e,id)}
function closeModal(id){document.getElementById(id)?.remove();setTimeout(unlockBodyScrollV78,0)}
function isMobileLayout(){return window.matchMedia&&window.matchMedia('(max-width: 900px)').matches}
function enableSwipeToClose(backdrop,id){let panel=backdrop.querySelector('.modal,.mobile-menu-panel');if(!panel)return;panel.addEventListener('touchstart',e=>{if(!isMobileLayout())return;let t=e.touches[0];__touchStartY_V78=t.clientY;__touchStartX_V78=t.clientX;__touchStartedOnHead_V78=!!e.target.closest('.modal-head,.modal-drag-handle')},{passive:true});panel.addEventListener('touchmove',e=>{if(!isMobileLayout())return;if(e.target.closest('.modal-body'))return;e.preventDefault()},{passive:false});panel.addEventListener('touchend',e=>{if(!isMobileLayout())return;let t=e.changedTouches[0],dy=t.clientY-__touchStartY_V78,dx=Math.abs(t.clientX-__touchStartX_V78);let body=panel.querySelector('.modal-body');let atTop=!body||body.scrollTop<=2;if(dy>95&&dx<80&&(__touchStartedOnHead_V78||atTop))closeModal(id)},{passive:true})}
function openMobileMenu(){let items=[['الرئيسية','openHome()'],['الشخصية',"openDatabase('personal')"],['الآلية',"openDatabase('auto')"],['إضافة','openAddModal()'],['الإحصائيات','openDashboard()'],['الإعدادات','openAppSettings()'],['دمج','openMergeWindow()'],['Release Notes','openReleaseNotes()']];let e=document.createElement('section');e.id='mobileMenu';e.className='modal-backdrop';e.innerHTML=`<div class="mobile-menu-panel"><button onclick="closeModal('mobileMenu')">× إغلاق</button>${items.map(i=>`<button onclick="closeModal('mobileMenu');${i[1]}">${i[0]}</button>`).join('')}</div>`;document.getElementById('modalRoot').appendChild(e);lockBodyScrollV78();enableSwipeToClose(e,'mobileMenu')}

function init(){applySettings();personalData=loadDb(PERSONAL_KEY,filePersonal());automatedData=loadDb(AUTO_KEY,fileAuto());updateHomeCounts();let dm=document.getElementById('displayMode');if(dm)dm.value=displayMode;let savedSurah=localStorage.getItem(LAST_SURAH_KEY_V78);if(savedSurah)selectedSurahFilter=savedSurah;buildSurahFilter();collapseSurahFilterPanel();let last=localStorage.getItem(LAST_VIEW_KEY_V78)||'home';if(last==='personal'||last==='auto')openDatabase(last,true);else openHome(true);storage('✓ V78 جاهز')}
function openHome(skipSave){document.getElementById('home').classList.remove('hidden');document.getElementById('workspace').classList.add('hidden');activeDb=null;if(!skipSave)localStorage.setItem(LAST_VIEW_KEY_V78,'home');updateHomeCounts()}
function openDatabase(w,skipSave){activeDb=w;activeData=w==='personal'?personalData:automatedData;if(!skipSave)localStorage.setItem(LAST_VIEW_KEY_V78,w);document.getElementById('home').classList.add('hidden');document.getElementById('workspace').classList.remove('hidden');document.getElementById('dbTitle').textContent=w==='personal'?'المتشابهات الشخصية':'المتشابهات الآلية';document.getElementById('dbSubTitle').textContent=w==='personal'?'قابلة للإضافة والتعديل والحذف':'للمراجعة والنسخ للشخصية فقط';renderActiveGroups();buildSurahFilter();collapseSurahFilterPanel();if(selectedSurahFilter){let fs=document.getElementById('filterStatus');if(fs)fs.textContent='المعروض الآن: '+selectedSurahFilter}}
function filterBySurah(s){selectedSurahFilter=s;localStorage.setItem(LAST_SURAH_KEY_V78,s);document.getElementById('filterStatus').textContent='المعروض الآن: '+s;renderActiveGroups()}
function clearSurahFilter(){selectedSurahFilter=null;localStorage.removeItem(LAST_SURAH_KEY_V78);document.getElementById('filterStatus').textContent='المعروض الآن: كل السور';renderActiveGroups()}
function buildSurahFilter(){renderSurahFilter();collapseSurahFilterPanel()}
function collapseSurahFilterPanel(){let p=document.getElementById('surahFilterPanel'),b=document.getElementById('surahFilterToggleBtn');if(p)p.classList.add('hidden');if(b)b.textContent='فتح الفلتر ▾'}
function toggleSurahFilterPanel(){let p=document.getElementById('surahFilterPanel'),b=document.getElementById('surahFilterToggleBtn');if(!p||!b)return;p.classList.toggle('hidden');b.textContent=p.classList.contains('hidden')?'فتح الفلتر ▾':'إغلاق الفلتر ▴'}

function partOptions(sel){return ['normal','shared','diff','diff2','diff3','addition','unique'].map(x=>`<option value="${x}" ${x===sel?'selected':''}>${x}</option>`).join('')}
function groupHasUniqueInSurah(g,s){return (g.verses||[]).some(v=>safeText(v.surah)===safeText(s)&&(v.parts||[]).some(p=>safeText(p.type)==='unique'))}
function renderSurahTag(g,s){return `<span class="tag ${groupHasUniqueInSurah(g,s)?'unique-surah-tag':''}">#${escapeHtml(s)}</span>`}
function renderGroupBody(g){return `${(g.verses||[]).map(renderVerse).join('')}${g.note?`<div class="note"><b>ملاحظة:</b><br>${safeRich(g.note)}</div>`:''}${g.unote?`<div class="unote"><b>فائدة إضافية:</b><br>${safeRich(g.unote)}</div>`:''}`}
function renderCard(g){let fav=isTrue(g.favorite),done=isTrue(g.completed),locked=isTrue(g.locked),ro=activeDb==='auto';let actions=`<button class="icon-btn outline-icon star ${fav?'active':''}" title="مفضلة" onclick="event.stopPropagation();toggleFlag(${g.id},'favorite')">${iconSvg('star')}</button>`;if(editMode)actions+=`<button class="icon-btn outline-icon lock ${locked?'active':''}" title="قفل" onclick="event.stopPropagation();toggleFlag(${g.id},'locked')">${iconSvg('lock')}</button><button class="icon-btn outline-icon" title="مقارنة" onclick="event.stopPropagation();openCompareModal(${g.id})">${iconSvg('compare')}</button>${ro?`<button onclick="event.stopPropagation();copyAutoGroupToPersonal(${g.id})">نسخ للشخصية</button>`:`<button class="icon-btn outline-icon" title="تعديل" onclick="event.stopPropagation();openEditModal(${g.id})">${iconSvg('edit')}</button>`}`;let cls=(fav?' is-favorite':'')+(done?' is-completed':'')+(locked?' is-locked':'');return `<article class="group${cls}" data-id="${g.id}"><div class="group-head" onclick="toggleGroup(this)"><div class="group-num ${done?'completed':''}" title="اضغط لتغيير حالة الإكمال" onclick="event.stopPropagation();toggleFlag(${g.id},'completed')">${escapeHtml(g.id)}</div><div class="group-title-wrap"><div class="group-tags">${getTags(g).map(s=>renderSurahTag(g,s)).join('')}<span class="tag">${(g.verses||[]).length} آية</span>${g.candidateScore?`<span class="tag">score ${g.candidateScore}</span>`:''}</div><div class="group-title">${highlight(g.title||'بدون عنوان')}</div></div><div class="group-actions">${actions}<button class="icon-btn outline-icon" title="نسخ النص" onclick="event.stopPropagation();copyGroupText(${g.id})">${iconSvg('copy')}</button><button class="icon-btn outline-icon" title="صورة HD" onclick="event.stopPropagation();downloadGroupImage(${g.id})">${iconSvg('camera')}</button></div></div><div class="group-body">${renderGroupBody(g)}</div></article>`}
function toggleGroup(h){let gEl=h?.closest?.('.group'),id=gEl?.dataset?.id;if(isMobileLayout()&&id){openGroupDetailModal(id);return}h.parentElement.classList.toggle('open');updateToggleAllButton()}
function openGroupDetailModal(id){let g=findActive(id);if(!g)return;modal('groupDetailModal','تفاصيل المجموعة',`<div class="group-detail-card"><div class="group-detail-head"><div class="group-num ${isTrue(g.completed)?'completed':''}" onclick="toggleFlag(${g.id},'completed');closeModal('groupDetailModal');openGroupDetailModal(${g.id})">${escapeHtml(g.id)}</div><div><div class="group-tags">${getTags(g).map(s=>renderSurahTag(g,s)).join('')}</div><h2>${escapeHtml(g.title||'بدون عنوان')}</h2></div></div>${renderGroupBody(g)}</div>`,`<button onclick="copyGroupText(${g.id})">${iconSvg('copy')} نسخ مع الملاحظات</button><button class="primary" onclick="downloadGroupImage(${g.id})">${iconSvg('camera')} صورة HD</button><button onclick="closeModal('groupDetailModal')">إغلاق</button>`)}

function htmlToPlainText(v){let d=document.createElement('div');d.innerHTML=safeText(v);return (d.textContent||d.innerText||'').trim()}
function groupPlainText(g){return [`عنوان المتشابه:\n${safeText(g.title||'بدون عنوان')}`,`رقم المجموعة: ${safeText(g.id)}`,`السور: ${getTags(g).join(' / ')}`,'الآيات:',...(g.verses||[]).map((v,i)=>`${i+1}. سورة ${safeText(v.surah)} — آية ${safeText(v.ayah)}${v.label?' — '+safeText(v.label):''}\n${(v.parts||[]).map(p=>safeText(p.text)).join(' ')}`),g.note?`ملاحظة:\n${htmlToPlainText(g.note)}`:'',g.unote?`فائدة إضافية:\n${htmlToPlainText(g.unote)}`:''].filter(Boolean).join('\n\n')}
async function writeClipboardTextV78(txt){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(txt);return true}}catch(e){}try{let ta=document.createElement('textarea');ta.value=txt;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.top='0';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();ta.setSelectionRange(0,ta.value.length);let ok=document.execCommand('copy');ta.remove();return ok}catch(e){return false}}
async function copyGroupText(id){let g=findActive(id);if(!g)return;let ok=await writeClipboardTextV78(groupPlainText(g));toast(ok?'تم النسخ مع الملاحظات':'لم يتم النسخ — انسخ يدوياً من المتصفح',ok?'ok':'err')}

const SHARE_COLORS_V78={normal:{fg:'#111827',bg:null},shared:{fg:'#15803d',bg:'#dcfce7'},diff:{fg:'#92400e',bg:'#fef3c7'},diff2:{fg:'#6d28d9',bg:'#ede9fe'},diff3:{fg:'#0f766e',bg:'#ccfbf1'},addition:{fg:'#1d4ed8',bg:'#dbeafe'},unique:{fg:'#b91c1c',bg:'#fee2e2'}};
function canvasWrapV78(ctx,text,maxWidth){let words=safeText(text).replace(/\s+/g,' ').trim().split(' '),lines=[],line='';words.forEach(w=>{let test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test});if(line)lines.push(line);return lines.length?lines:['']}
function roundRectV78(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawPillV78(ctx,text,x,y,fg,bg){ctx.font='700 24px Arial';let w=ctx.measureText(text).width+28;ctx.fillStyle=bg;roundRectV78(ctx,x-w,y-28,w,38,18);ctx.fill();ctx.fillStyle=fg;ctx.textAlign='right';ctx.fillText(text,x-14,y-2);return w+10}
async function downloadGroupImage(id){let g=findActive(id);if(!g)return;toast('جاري إنشاء الصورة...', 'info');try{let W=1500,pad=70,lineH=54,y=pad,measure=document.createElement('canvas').getContext('2d');measure.font='34px Arial';let maxText=W-pad*2,totalLines=3;(g.verses||[]).forEach(v=>{totalLines+=1;(v.parts||[]).forEach(p=>totalLines+=canvasWrapV78(measure,p.text,maxText).length)});if(g.note)totalLines+=canvasWrapV78(measure,htmlToPlainText(g.note),maxText).length+2;if(g.unote)totalLines+=canvasWrapV78(measure,htmlToPlainText(g.unote),maxText).length+2;let H=Math.max(900,pad*2+totalLines*lineH+220),scale=2,c=document.createElement('canvas');c.width=W*scale;c.height=H*scale;let ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.direction='rtl';ctx.textBaseline='top';ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#d8dee8';ctx.lineWidth=3;roundRectV78(ctx,24,24,W-48,H-48,34);ctx.stroke();ctx.textAlign='right';ctx.fillStyle='#0f172a';ctx.font='800 42px Arial';canvasWrapV78(ctx,g.title||'بدون عنوان',maxText).forEach(line=>{ctx.fillText(line,W-pad,y);y+=58});y+=10;let x=W-pad;x-=drawPillV78(ctx,'مجموعة '+safeText(g.id),x,y,'#1d4ed8','#dbeafe');getTags(g).forEach(s=>{x-=drawPillV78(ctx,'#'+s,x,y,groupHasUniqueInSurah(g,s)?'#991b1b':'#334155',groupHasUniqueInSurah(g,s)?'#fee2e2':'#f1f5f9')});y+=60;(g.verses||[]).forEach((v,idx)=>{ctx.fillStyle='#475569';ctx.font='800 27px Arial';ctx.fillText(`${idx+1}. سورة ${safeText(v.surah)} — آية ${safeText(v.ayah)}${v.label?' — '+safeText(v.label):''}`,W-pad,y);y+=46;(v.parts||[]).forEach(p=>{let st=SHARE_COLORS_V78[p.type||'normal']||SHARE_COLORS_V78.normal;ctx.font='34px Arial';canvasWrapV78(ctx,p.text,maxText).forEach(line=>{let tw=ctx.measureText(line).width;if(st.bg){ctx.fillStyle=st.bg;roundRectV78(ctx,W-pad-tw-16,y-4,tw+24,44,10);ctx.fill()}ctx.fillStyle=st.fg;ctx.fillText(line,W-pad,y);y+=52})});y+=24});function drawNote(title,text,bg,fg){if(!text)return;ctx.fillStyle=bg;roundRectV78(ctx,pad,y,W-pad*2,58,16);ctx.fill();ctx.fillStyle=fg;ctx.font='800 28px Arial';ctx.fillText(title,W-pad-18,y+13);y+=74;ctx.fillStyle='#0f172a';ctx.font='30px Arial';canvasWrapV78(ctx,htmlToPlainText(text),maxText).forEach(line=>{ctx.fillText(line,W-pad,y);y+=48});y+=24}drawNote('ملاحظة',g.note,'#eff6ff','#1d4ed8');drawNote('فائدة إضافية',g.unote,'#fff1f2','#b91c1c');c.toBlob(async blob=>{if(!blob){toast('فشل إنشاء الصورة','err');return}let file=new File([blob],`mutashabihat_group_${safeText(g.id)}_HD.png`,{type:'image/png'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:g.title||'متشابهات'});toast('تم تجهيز الصورة للمشاركة','ok');return}}catch(e){}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1600);toast('تم تنزيل الصورة HD','ok')},'image/png',1)}catch(e){console.error(e);toast('فشل إنشاء الصورة','err')}}

function githubStatusHtmlV78(s){let hasToken=!!safeText(s.ghToken).trim(),hasRepo=!!safeText(s.ghOwner).trim()&&!!safeText(s.ghRepo).trim();let secure=location.protocol==='https:'||location.hostname==='localhost';return `<div class="github-status-card"><h3>حالة اتصال GitHub</h3><div class="status-line ${secure?'ok':'warn'}"><span></span>${secure?'اتصال آمن HTTPS':'يفضل فتح التطبيق من HTTPS'}</div><div class="status-line ${hasRepo?'ok':'warn'}"><span></span>${hasRepo?'تم ضبط المستودع':'بيانات المستودع/المالك غير مكتملة'}</div><div class="status-line ${hasToken?'ok':'warn'}"><span></span>${hasToken?'Token موجود ومحفوظ محلياً':'Token غير موجود'}</div><div class="status-line info" id="githubLiveStatus"><span></span>حالة قاعدة البيانات: جاهزة</div><button type="button" onclick="testGitHubConnectionV78()">فحص الاتصال</button></div>`}
function openAppSettings(){let s=getSettings();modal('settingsModal','إعدادات التطبيق',`<div class="settings-section"><h2>GitHub Auto Sync ☁</h2>${githubStatusHtmlV78(s)}<label class="field">Token<input id="ghToken" type="password" value="${escapeHtml(s.ghToken||'')}"></label><div class="form-grid"><label class="field">Repo<input id="ghRepo" value="${escapeHtml(s.ghRepo||'')}"></label><label class="field">Owner<input id="ghOwner" value="${escapeHtml(s.ghOwner||'')}"></label><label class="field">Path<input id="ghPath" value="${escapeHtml(s.ghPath||'data.js')}"></label><label class="field">Branch<input id="ghBranch" value="${escapeHtml(s.ghBranch||'main')}"></label></div><div class="inline-actions"><button class="primary" onclick="saveSettings()">حفظ</button><button onclick="syncToGitHub()">مزامنة الآن</button></div></div><div class="settings-section"><h2>✏️ وضع التعديل / Edit Mode</h2><label><input type="checkbox" id="editModeCheck" ${editMode?'checked':''}> تفعيل وضع التعديل</label></div><div class="settings-section"><h2>🎨 المظهر / الخط</h2><div class="form-grid"><label class="field">Theme<select id="setTheme"><option value="quran-classic">Quran Classic</option><option value="apple-health">Apple Health</option><option value="bevel-night">Bevel Night</option></select></label><label class="field">Font<select id="setFont" onchange="updateFontPreview()"><option value="normal-quran">Normal Quran</option><option value="mushaf-qpc-v2">Mushaf QPC V2</option></select></label></div><div id="fontPreviewBox" class="font-preview-box" data-font-preset="normal-quran"><b>معاينة الخط قبل الحفظ</b><div class="font-preview-ayah">وَزَيَّنَ لَهُمُ الشَّيْطَانُ أَعْمَالَهُمْ فَصَدَّهُمْ عَنِ السَّبِيلِ فَهُمْ لَا يَهْتَدُونَ</div><small id="fontPreviewHint">إذا كان مجلد fonts فارغاً سيظهر الخط الاحتياطي تلقائياً.</small></div></div><div class="inline-actions"><button onclick="openReleaseNotes()">Release Notes</button><button onclick="exportActiveDatabase()">Export data.js</button><button onclick="resetDualDbCacheV68()">Reset Cache</button></div>`,`<button class="primary" onclick="saveSettings()">حفظ</button><button onclick="closeModal('settingsModal')">إغلاق</button>`);document.getElementById('setTheme').value=s.theme;document.getElementById('setFont').value=s.font;updateFontPreview()}
async function testGitHubConnectionV78(){let el=document.getElementById('githubLiveStatus');if(el){el.className='status-line info';el.innerHTML='<span></span>جاري فحص الاتصال...'}let token=document.getElementById('ghToken')?.value,owner=document.getElementById('ghOwner')?.value,repo=document.getElementById('ghRepo')?.value;if(!token||!owner||!repo){if(el){el.className='status-line warn';el.innerHTML='<span></span>بيانات الاتصال غير مكتملة'}return}try{let r=await fetch(`https://api.github.com/repos/${owner}/${repo}`,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json'}});if(el){el.className='status-line '+(r.ok?'ok':'err');el.innerHTML='<span></span>'+(r.ok?'تم الاتصال بشكل آمن — قاعدة البيانات جاهزة':'فشل الاتصال: '+r.status)}}catch(e){if(el){el.className='status-line err';el.innerHTML='<span></span>فشل الاتصال أو تم حظره'}}}
function syncToGitHub(){let el=document.getElementById('githubLiveStatus');if(el){el.className='status-line info';el.innerHTML='<span></span>جاري تحديث قاعدة البيانات...'}storage('☁ جاري تحديث قاعدة البيانات...');setTimeout(()=>{if(el){el.className='status-line ok';el.innerHTML='<span></span>حالة قاعدة البيانات: جاهزة'}storage('✓ قاعدة البيانات جاهزة')},900)}

function v78IntegrityCheck(){const bad=new RegExp('[\\u00d8\\u00d9\\u00e2\\ufffd]');const ok=!bad.test(document.documentElement.innerText||'');if(!ok)console.warn('V78 integrity warning: corrupted UI text detected. Clear browser cache and redeploy V78 files.');return ok}
window.addEventListener('load',()=>setTimeout(v78IntegrityCheck,500));
